/**
 * Server functions for the "Recalibrate" admin action.
 *
 * Root cause it addresses: the calibration report shipped in the app is
 * a static JSON generated by `worker/calibrate.py`. Operators need to
 * kick that pass off remotely, watch it progress, and see the fresh
 * report without a redeploy. The Python worker exposes three endpoints
 * (POST /calibrate, GET /calibrate/status, GET /calibration-report),
 * gated by VALIDATION_WORKER_TOKEN. Each server fn below is admin-gated
 * in the app so only users with the `admin` role can invoke it.
 */
import { HttpMethod } from "@/lib/constants";
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const StatusSchema = z.object({
  state: z.enum(["idle", "running", "done", "error"]),
  jobId: z.string().nullable().optional(),
  startedAt: z.number().nullable().optional(),
  finishedAt: z.number().nullable().optional(),
  progress: z.object({
    step: z.number(),
    total: z.number(),
    message: z.string(),
  }),
  lines: z.array(z.string()).default([]),
  error: z.string().nullable().optional(),
});

const StartSchema = StatusSchema.extend({
  status: z.enum(["started", "already-running"]),
});

export type CalibrationStatus = z.infer<typeof StatusSchema>;
export type CalibrationStart = z.infer<typeof StartSchema>;

function readEnv(): { url: string; token: string | undefined } {
  const url = process.env.VALIDATION_WORKER_URL;

  if (!url) throw new Error("VALIDATION_WORKER_URL is not set");

  return { url: url.replace(/\/$/, ""), token: process.env.VALIDATION_WORKER_TOKEN };
}

function authHeaders(token: string | undefined): Record<string, string> {
  return token ? { authorization: `Bearer ${token}` } : {};
}

// Kept inline (not a helper) so the SupabaseClient type flows through the
// generated Database types without needing to hand-shape the parameter.
async function assertAdminInline(
  supabase: { from: (t: string) => unknown },
  userId: string,
): Promise<void> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const q: any = await (supabase.from("user_roles") as any)
    .select("role")
    .eq("user_id", userId)
    .eq("role", "admin")
    .limit(1);

  if (q?.error) throw new Error(`role-check failed: ${q.error.message}`);

  if (!q?.data || q.data.length === 0) throw new Error("E_SEC_ROLE_DENIED");
}

export const startCalibration = createServerFn({ method: HttpMethod.Post })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }): Promise<CalibrationStart> => {
    await assertAdminInline(context.supabase, context.userId);
    const { url, token } = readEnv();
    const res = await fetch(`${url}/calibrate`, {
      method: HttpMethod.Post,
      headers: authHeaders(token),
    });

    if (res.ok === false) throw new Error(`worker /calibrate returned ${res.status}`);

    return StartSchema.parse(await res.json());
  });

export const getCalibrationJobStatus = createServerFn({ method: HttpMethod.Get })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }): Promise<CalibrationStatus> => {
    await assertAdminInline(context.supabase, context.userId);
    const { url, token } = readEnv();
    const res = await fetch(`${url}/calibrate/status`, { headers: authHeaders(token) });

    if (res.ok === false) throw new Error(`worker /calibrate/status returned ${res.status}`);

    return StatusSchema.parse(await res.json());
  });

// Loose schema: the report shape is worker-owned and evolves; the admin
// UI renders whatever fields it recognises. Keep the return type as
// `Record<string, any>` so TanStack's serializable check accepts it.
const ReportSchema = z.record(z.any());
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type CalibrationReport = { per_kind: Record<string, any>; detail?: any[] };

export const getCalibrationReport = createServerFn({ method: HttpMethod.Get })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    await assertAdminInline(context.supabase, context.userId);
    const { url, token } = readEnv();
    const res = await fetch(`${url}/calibration-report`, { headers: authHeaders(token) });

    if (res.ok === false) throw new Error(`worker /calibration-report returned ${res.status}`);

    return ReportSchema.parse(await res.json());
  });
