import { CatalogCategoryIdType, type CatalogTool } from "./types";

export const CATALOG_TOOLS: readonly CatalogTool[] = [
  // --- PRESENCE / ABSENCE ---
  {
    id: "tool-area",
    displayCode: "T101",
    name: "Area",
    category: CatalogCategoryIdType.PresenceAbsence,
    iconName: "Square",
    badge: "B/W Specific Area",
    shortDesc: "Measures black or white pixel quantity inside the ROI.",
    fullDesc:
      "Binarizes the inspection region with an intensity threshold and counts pixels matching target color. Evaluates whether total measured area satisfies min/max limits.",
    detectionFeatures: [
      "Binarization Threshold",
      "Auto Set Intensity",
      "Histogram Analysis",
      "Multi-Shape ROI",
    ],
    judgmentCriteria: ["Measured Pixel Area", "Upper Limit", "Lower Limit", "Pass / Fail Verdict"],
    targetRoute: "/setup/rules",
    ruleMatcher: "area",
    isPreferred: true,
  },
  {
    id: "tool-pattern-presence",
    displayCode: "T102",
    name: "Pattern Match (Shading)",
    category: CatalogCategoryIdType.PresenceAbsence,
    iconName: "Sparkles",
    badge: "Normalized Correlation",
    shortDesc: "Verifies workpiece presence via template correlation score.",
    fullDesc:
      "Searches the defined search region for registered master patterns. Evaluates match similarity score and count against acceptable thresholds.",
    detectionFeatures: [
      "Angle Range (±180°)",
      "Search Sensitivity",
      "Min Match %",
      "Detection Count",
    ],
    judgmentCriteria: ["Match Percentage (%)", "Detected Count", "Position Tolerance (X/Y)"],
    targetRoute: "/setup/rules",
    ruleMatcher: "pattern",
  },
  {
    id: "tool-blob-presence",
    displayCode: "T109",
    name: "Binary Blob",
    category: CatalogCategoryIdType.PresenceAbsence,
    iconName: "Shapes",
    badge: "Connected Components",
    shortDesc: "Detects presence of parts or voids by grouping connected pixels.",
    fullDesc:
      "Extracts connected pixel clusters (blobs) from binary image. Measures count, area, perimeter, and centroid coordinates to verify part presence or missing holes.",
    detectionFeatures: [
      "Dark / Light Extraction",
      "Min / Max Area Filter",
      "8-Way Connectivity",
      "Centroid X/Y",
    ],
    judgmentCriteria: ["Total Blob Count", "Primary Blob Area", "Circularity Gate"],
    targetRoute: "/setup/rules",
    ruleMatcher: "blob",
  },
  {
    id: "tool-intensity",
    displayCode: "T113",
    name: "Intensity / Luminance",
    category: CatalogCategoryIdType.PresenceAbsence,
    iconName: "Sun",
    badge: "Mean Brightness",
    shortDesc: "Measures average brightness and contrast within the ROI.",
    fullDesc:
      "Computes mean grayscale luminance and standard deviation across pixels in the region. Validates proper lighting, coating presence, or surface finish.",
    detectionFeatures: [
      "Mean Grayscale Level",
      "Standard Deviation",
      "Saturation Check",
      "RGB Channel Split",
    ],
    judgmentCriteria: ["Mean Intensity (0-255)", "Upper / Lower Limits", "Uniformity Index"],
    targetRoute: "/setup/rules",
    ruleMatcher: "intensity",
  },

  // --- FLAW DETECTION ---
  {
    id: "tool-defect",
    displayCode: "T108",
    name: "Defect Detection",
    category: CatalogCategoryIdType.FlawDetection,
    iconName: "AlertOctagon",
    badge: "Total Defect Area",
    shortDesc: "Detects surface scratches, dirt, burrs, cracks, and stains.",
    fullDesc:
      "Compares workpiece image against local background variance to extract flaws, cracks, burrs, or foreign particles. Aggregates defect area and severity.",
    detectionFeatures: [
      "Flaw Sensitivity",
      "Filter Size",
      "Dark / Bright Flaw Separation",
      "Edge Exclusion Margin",
    ],
    judgmentCriteria: ["Total Defect Area", "Max Single Flaw Size", "Defect Quantity Count"],
    targetRoute: "/setup/rules",
    ruleMatcher: "defect",
    isPreferred: true,
  },
  {
    id: "tool-grayscale-blob",
    displayCode: "T110",
    name: "Grayscale Blob",
    category: CatalogCategoryIdType.FlawDetection,
    iconName: "CircleDot",
    badge: "Contrast with Background",
    shortDesc: "Finds subtle contrast variations, discolorations, and stains.",
    fullDesc:
      "Analyzes localized contrast gradients to isolate subtle defects and surface stains that do not produce sharp binary transitions.",
    detectionFeatures: [
      "Dynamic Thresholding",
      "Local Contrast Gain",
      "Noise Rejection",
      "Multi-Level Slicing",
    ],
    judgmentCriteria: ["Defect Contrast Level", "Particle Area", "Aspect Ratio Limit"],
    targetRoute: "/setup/rules",
    ruleMatcher: "grayscale",
  },

  // --- ALIGNMENT ---
  {
    id: "tool-edge-position",
    displayCode: "T104",
    name: "Edge Position",
    category: CatalogCategoryIdType.Alignment,
    iconName: "MoveHorizontal",
    badge: "Sub-pixel Locator",
    shortDesc: "Accurately locates single 1D edge position in X or Y.",
    fullDesc:
      "Scans along a directional profile vector to detect high-contrast transition points with sub-pixel interpolation. Supplies datum coordinates.",
    detectionFeatures: [
      "Scan Direction (0-360°)",
      "Dark→Light / Light→Dark",
      "Edge Filter Width",
      "Peak Interpolation",
    ],
    judgmentCriteria: [
      "Position X / Y (px/μm)",
      "Edge Contrast Strength",
      "Positional Offset Limit",
    ],
    targetRoute: "/setup/rules",
    ruleMatcher: "edge",
    isPreferred: true,
  },
  {
    id: "tool-shapetrax3",
    displayCode: "T103",
    name: "ShapeTrax3",
    category: CatalogCategoryIdType.Alignment,
    iconName: "Compass",
    badge: "Contour Geometric Match",
    shortDesc: "Robust shape alignment using edge vector contours.",
    fullDesc:
      "Extracts contour edge vectors to recognize and locate target geometry. Highly resilient to illumination changes, occlusion, and surface variations.",
    detectionFeatures: [
      "Coarse / Fine Extraction",
      "Rotational Invariance (±180°)",
      "Scale Invariance (80-120%)",
      "Feature Eraser",
    ],
    judgmentCriteria: ["Geometric Match %", "Center X/Y Position", "Rotation Angle (deg)"],
    targetRoute: "/setup/rules",
    ruleMatcher: "shape",
  },
  {
    id: "tool-profile-position",
    displayCode: "T111",
    name: "Profile Position",
    category: CatalogCategoryIdType.Alignment,
    iconName: "Activity",
    badge: "1D Peak Locator",
    shortDesc: "Finds peak intensity or edge boundary along a 1D scan line.",
    fullDesc:
      "Projects 2D image pixel strip onto a 1D intensity profile curve to locate peaks, valleys, and zero-crossing points with sub-pixel precision.",
    detectionFeatures: [
      "Profile Projection Width",
      "Derivative Filter",
      "Peak Threshold",
      "Sub-pixel Fit",
    ],
    judgmentCriteria: ["Peak Coordinate", "Peak Amplitude", "Edge Count"],
    targetRoute: "/setup/rules",
    ruleMatcher: "profile",
  },

  // --- MEASUREMENT & COUNT ---
  {
    id: "tool-edge-width",
    displayCode: "T105",
    name: "Edge Width",
    category: CatalogCategoryIdType.MeasurementCount,
    iconName: "Maximize2",
    badge: "Caliper Distance",
    shortDesc: "Measures spacing or thickness between two detected edges.",
    fullDesc:
      "Scans across the target to detect outer or inner opposing edge boundaries and computes linear caliper distance with sub-pixel resolution.",
    detectionFeatures: [
      "Outer Gap / Inner Gap",
      "Scan Vector Direction",
      "Edge Sensitivity %",
      "Filter Kernel Size",
    ],
    judgmentCriteria: [
      "Measured Width (px/mm)",
      "Upper Tolerance",
      "Lower Tolerance",
      "Pass / Fail Verdict",
    ],
    targetRoute: "/setup/rules",
    ruleMatcher: "width",
    isPreferred: true,
  },
  {
    id: "tool-edge-pitch",
    displayCode: "T106",
    name: "Edge Pitch",
    category: CatalogCategoryIdType.MeasurementCount,
    iconName: "AlignJustify",
    badge: "Lead / Pin Pitch",
    shortDesc: "Measures pitch and spacing across repeating pin arrays.",
    fullDesc:
      "Detects periodic multi-edge structures (such as IC leads, connector pins, comb teeth) and calculates maximum, minimum, and average pitch intervals.",
    detectionFeatures: [
      "Center Pitch / Gap Pitch",
      "Multi-Peak Extraction",
      "Auto Period Estimator",
      "Spurious Filter",
    ],
    judgmentCriteria: ["Pitch Count", "Average Pitch", "Max Pitch Deviation", "Min Pitch Limit"],
    targetRoute: "/setup/rules",
    ruleMatcher: "pitch",
  },
  {
    id: "tool-edge-pairs",
    displayCode: "T107",
    name: "Edge Pairs",
    category: CatalogCategoryIdType.MeasurementCount,
    iconName: "Split",
    badge: "Pair Spacing",
    shortDesc: "Measures distance between specific edge transition pairs.",
    fullDesc:
      "Pairs complementary Dark→Light and Light→Dark edge steps to inspect slot widths, keyway openings, and track thicknesses.",
    detectionFeatures: [
      "1st / 2nd Edge Pairing",
      "Transition Polarities",
      "Scan Line Direction",
      "Pair Margin",
    ],
    judgmentCriteria: ["Pair Distance", "Pair Count", "Midpoint Deviation"],
    targetRoute: "/setup/rules",
    ruleMatcher: "pair",
  },
  {
    id: "tool-profile-width",
    displayCode: "T112",
    name: "Profile Width",
    category: CatalogCategoryIdType.MeasurementCount,
    iconName: "SlidersHorizontal",
    badge: "Profile Caliper",
    shortDesc: "Measures width between 1D profile threshold crossings.",
    fullDesc:
      "Calculates distance between leading and trailing edge transitions on a projected 1D intensity waveform.",
    detectionFeatures: [
      "Threshold Crossing Mode",
      "Peak-to-Valley Spacing",
      "Smoothing Kernel",
      "Dynamic Level",
    ],
    judgmentCriteria: ["Profile Width", "Upper / Lower Limits", "Baseline Level"],
    targetRoute: "/setup/rules",
    ruleMatcher: "profile",
  },

  // --- ID & OCR / OCV ---
  {
    id: "tool-code-reader",
    displayCode: "T115",
    name: "1D / 2D Code Reader",
    category: CatalogCategoryIdType.IdOcr,
    iconName: "QrCode",
    badge: "Barcode & DataMatrix",
    shortDesc: "Decodes 1D barcodes and 2D DataMatrix / QR codes.",
    fullDesc:
      "Decodes linear barcodes (Code 128, Code 39, EAN) and 2D matrix codes (DataMatrix ECC200, QR Code, PDF417). Checks code grading and string contents.",
    detectionFeatures: [
      "Symbology Auto-Detect",
      "Mirror & Inversion Mode",
      "Print Quality Grade",
      "Cell Size Filter",
    ],
    judgmentCriteria: ["Decoded String Content", "Quality Grade (A-F)", "Checksum Verification"],
    targetRoute: "/setup/rules",
    ruleMatcher: "code",
    isPreferred: true,
  },
  {
    id: "tool-ocr2",
    displayCode: "T114",
    name: "OCR2 Character Recognition",
    category: CatalogCategoryIdType.IdOcr,
    iconName: "FileText",
    badge: "Optical Character Rec.",
    shortDesc: "Reads printed characters, date codes, and lot numbers.",
    fullDesc:
      "Extracts printed characters using font dictionaries or custom neural models. Matches extracted strings against regex formats or master serials.",
    detectionFeatures: [
      "Character Segmentation",
      "Font Library Match",
      "Regex Expression Gate",
      "Dot Matrix Support",
    ],
    judgmentCriteria: [
      "Extracted String Match",
      "Min Character Confidence %",
      "Character Count Check",
    ],
    targetRoute: "/setup/rules",
    ruleMatcher: "ocr",
  },

  // --- POSITION & SETUP ---
  {
    id: "tool-roi-setup",
    displayCode: "S201",
    name: "ROI Geometry & Masks",
    category: CatalogCategoryIdType.PositionAdjustment,
    iconName: "Layers",
    badge: "Multi-Geometry ROI",
    shortDesc: "Configures inspection regions (Rect, Circle, Ring, Polygon) & Masks 0-3.",
    fullDesc:
      "Interactive editor for drawing inspection boundaries and exclusion masks. Supports dynamic origin anchor tracking linked to alignment tools.",
    detectionFeatures: [
      "Rectangle / Rotated Rect",
      "Circle / Oval / Ring",
      "Polygon & Polyline",
      "Mask Exclusion 0-3",
    ],
    judgmentCriteria: ["Bounding Coordinates", "Active Mask Count", "Anchor Rule Link"],
    targetRoute: "/setup/roi",
    isPreferred: true,
  },
  {
    id: "tool-reference-setup",
    displayCode: "S202",
    name: "Reference Image Setup",
    category: CatalogCategoryIdType.PositionAdjustment,
    iconName: "Image",
    badge: "Golden Master Image",
    shortDesc: "Registers golden reference images and performs pixel calibration.",
    fullDesc:
      "Captures or uploads golden master workpiece images, sets reference zero datum, and calibrates pixel-to-micron scaling factors.",
    detectionFeatures: [
      "Live Sensor Frame Grab",
      "File Import (BMP/PNG/JPG)",
      "Pixel/μm Scaling",
      "Golden Template Store",
    ],
    judgmentCriteria: ["Image Resolution (W×H)", "Color Space", "Calibration Status"],
    targetRoute: "/setup/reference",
  },
  {
    id: "tool-camera-setup",
    displayCode: "S203",
    name: "Camera Sensor Acquisition",
    category: CatalogCategoryIdType.PositionAdjustment,
    iconName: "Camera",
    badge: "Sensor Driver & Trigger",
    shortDesc: "Controls sensor exposure, analog gain, frame rate, and triggers.",
    fullDesc:
      "Configures industrial camera sensors (Daheng, Basler, FLIR), software/hardware trigger lines, exposure timing, and pixel gain registers.",
    detectionFeatures: [
      "Exposure Time (μs)",
      "Analog Gain (dB)",
      "Hardware Strobe Sync",
      "Software Test Trigger",
    ],
    judgmentCriteria: ["Sensor Link State", "Dropped Frame Rate", "Trigger Latency (ms)"],
    targetRoute: "/setup/camera",
  },
  {
    id: "tool-lighting-setup",
    displayCode: "S204",
    name: "Illumination Controller",
    category: CatalogCategoryIdType.PositionAdjustment,
    iconName: "SunMedium",
    badge: "LED Channels & Strobe",
    shortDesc: "Sets multi-channel LED lighting levels and strobe pulses.",
    fullDesc:
      "Controls ring, bar, coaxial, and backlight LED channels with calibrated brightness values and trigger strobe synchronization.",
    detectionFeatures: [
      "Multi-Channel Sliders",
      "Strobe Duration (μs)",
      "Preset Scene Storage",
      "Overdrive Protection",
    ],
    judgmentCriteria: ["Channel Voltage/Current", "Thermal Limit Status"],
    targetRoute: "/settings/lighting",
  },

  // --- MATHEMATICAL OPERATIONS ---
  {
    id: "tool-functions",
    displayCode: "M301",
    name: "Custom Function Library",
    category: CatalogCategoryIdType.MathematicalOperations,
    iconName: "Code",
    badge: "JavaScript Expressions",
    shortDesc: "Executes custom mathematical logic over inspection results.",
    fullDesc:
      "Author and execute reusable JS expressions to compute derived tolerances, geometric relations, statistical distributions, and custom pass/fail formulas.",
    detectionFeatures: [
      "Context Injector (Rules/Results)",
      "JSON Import / Export",
      "Live Evaluation Sandbox",
      "Persistence Store",
    ],
    judgmentCriteria: ["Expression Return Value", "Runtime Execution Time (ms)", "Exception Trap"],
    targetRoute: "/setup/functions",
    isPreferred: true,
  },
  {
    id: "tool-chain-events",
    displayCode: "M302",
    name: "Chain Events & Sequencing",
    category: CatalogCategoryIdType.MathematicalOperations,
    iconName: "Workflow",
    badge: "Rule Flow Controller",
    shortDesc: "Defines event sequences, trigger rules, and conditional branching.",
    fullDesc:
      "Configures sequential dependency graphs where the execution and coordinates of downstream tools depend on upstream tool pass/fail verdicts.",
    detectionFeatures: [
      "Pre-Rule Dependency DAG",
      "Branching Verdicts",
      "Cycle Prevention",
      "Execution Cascade",
    ],
    judgmentCriteria: ["Total Chain Latency", "Cycle Status", "Gated Verdict"],
    targetRoute: "/setup/chain-events",
  },
] as const;
