"""Central registry of typed error codes.

Anchor: spec/21-app/40-error-manage.md §2, §5.

Rule: inventing an `E_*` code at a call site is `E_BUG_UNKNOWN_CODE`. Every code
that crosses a boundary MUST exist in this enum. Adding a code requires (a) an
entry here, (b) a UI mapping in spec 37/38/39, (c) a test in spec 45.
"""
from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    # --- Root DB / migrations (spec 21, 26 ; gates A-01..A-03) ---
    E_ROOT_DB_MISSING = "E_ROOT_DB_MISSING"
    E_DB_MIGRATION_GAP = "E_DB_MIGRATION_GAP"
    E_DB_MIGRATION_NONIDEMPOTENT = "E_DB_MIGRATION_NONIDEMPOTENT"
    E_DB_PARTIAL_WRITE = "E_DB_PARTIAL_WRITE"

    # --- Capture (spec 14 ; gates A-03..A-05) ---
    E_CAP_TRIGGER_HW_UNAVAILABLE = "E_CAP_TRIGGER_HW_UNAVAILABLE"
    E_CAP_FPS_REGRESSION = "E_CAP_FPS_REGRESSION"
    E_CAP_PENDING_WRITE = "E_CAP_PENDING_WRITE"

    # --- Dispatch / worker (spec 13, 27, 36 ; gates A-02, A-04..A-08) ---
    E_WORKER_POOL_MISSIZED = "E_WORKER_POOL_MISSIZED"
    E_WORKER_SHARED_MUTATION = "E_WORKER_SHARED_MUTATION"
    E_INSTRUCTION_SCHEMA = "E_INSTRUCTION_SCHEMA"
    E_INSTRUCTION_TAMPERED = "E_INSTRUCTION_TAMPERED"
    E_CONFIG_ORDER_VIOLATION = "E_CONFIG_ORDER_VIOLATION"
    E_CONFIG_MISSING = "E_CONFIG_MISSING"
    E_CONFIG_TYPE = "E_CONFIG_TYPE"
    E_CONFIG_RANGE = "E_CONFIG_RANGE"
    E_CONFIG_ENUM = "E_CONFIG_ENUM"
    E_DISPATCH_LIFECYCLE_MOVE = "E_DISPATCH_LIFECYCLE_MOVE"
    E_DISPATCH_RECLAIM = "E_DISPATCH_RECLAIM"

    # --- Results / rotation (spec 24 ; gate A-09) ---
    E_RESULT_REFERENCE_PATH = "E_RESULT_REFERENCE_PATH"
    E_RESULTS_ROTATE_MISSED = "E_RESULTS_ROTATE_MISSED"
    E_RESULT_RENDER_DRIFT = "E_RESULT_RENDER_DRIFT"

    # --- Logging / observability (spec 41, 42 ; gates A-15..A-19) ---
    E_LOG_CLOCK_REGRESSION = "E_LOG_CLOCK_REGRESSION"
    E_LOG_SCHEMA_VIOLATION = "E_LOG_SCHEMA_VIOLATION"
    E_OBS_CARDINALITY_EXPLOSION = "E_OBS_CARDINALITY_EXPLOSION"

    # --- Health / security (spec 42, 44 ; gates A-13, A-18..A-20) ---
    E_HEALTH_READY_UNAUTHORIZED = "E_HEALTH_READY_UNAUTHORIZED"
    E_SEC_SECRET_LEAK = "E_SEC_SECRET_LEAK"
    E_SEC_HEALTH_OVEREXPOSED = "E_SEC_HEALTH_OVEREXPOSED"
    E_SEC_BUNDLE_MISMATCH = "E_SEC_BUNDLE_MISMATCH"
    E_SEC_EGRESS_DETECTED = "E_SEC_EGRESS_DETECTED"
    # spec 21-app/44 §5, §Table — full 13-code E_SEC_* taxonomy (F-45).
    E_SEC_UNAPPROVED_EGRESS = "E_SEC_UNAPPROVED_EGRESS"
    E_SEC_BOUNDARY_UNVALIDATED = "E_SEC_BOUNDARY_UNVALIDATED"
    E_SEC_IMAGE_LOGGED = "E_SEC_IMAGE_LOGGED"
    E_SEC_RETENTION_PARTIAL = "E_SEC_RETENTION_PARTIAL"
    E_SEC_PATH_ESCAPE = "E_SEC_PATH_ESCAPE"
    E_SEC_CONSENT_MISSING = "E_SEC_CONSENT_MISSING"
    E_SEC_CONSENT_REUSED = "E_SEC_CONSENT_REUSED"
    E_SEC_REDACTION_BYPASSED = "E_SEC_REDACTION_BYPASSED"
    E_SEC_SECRET_PERSISTED = "E_SEC_SECRET_PERSISTED"
    E_SEC_HEALTH_LEAK = "E_SEC_HEALTH_LEAK"
    E_SEC_HEALTH_TOKEN_WEAK = "E_SEC_HEALTH_TOKEN_WEAK"
    E_SEC_HEALTH_TOKEN_ROTATION_SILENT = "E_SEC_HEALTH_TOKEN_ROTATION_SILENT"
    E_SEC_TIMING_UNSAFE_COMPARE = "E_SEC_TIMING_UNSAFE_COMPARE"

    # --- Rule engine / tolerances (spec 21-app/33, /34 ; gates A-04, A-05) ---
    E_RULE_BELOW_THRESHOLD = "E_RULE_BELOW_THRESHOLD"
    E_RULE_OUT_OF_RANGE = "E_RULE_OUT_OF_RANGE"
    E_RULE_NO_MATCH = "E_RULE_NO_MATCH"
    E_RULE_TIMEOUT = "E_RULE_TIMEOUT"
    E_RULE_BAD_INPUT = "E_RULE_BAD_INPUT"
    E_RULE_UNSUPPORTED = "E_RULE_UNSUPPORTED"
    E_RULE_DISABLED_IN_V1 = "E_RULE_DISABLED_IN_V1"
    E_TOLERANCE_INVALID = "E_TOLERANCE_INVALID"
    E_TOLERANCE_INCOMPATIBLE = "E_TOLERANCE_INCOMPATIBLE"
    E_TOLERANCE_UNRESOLVED = "E_TOLERANCE_UNRESOLVED"
    E_TOLERANCE_CROSS_TASK = "E_TOLERANCE_CROSS_TASK"



    E_AI_VERDICT_LEAK = "E_AI_VERDICT_LEAK"
    E_AI_STUB_INVOKED = "E_AI_STUB_INVOKED"
    E_AI_MODEL_MISSING = "E_AI_MODEL_MISSING"
    E_AI_FABRICATED_OPINION = "E_AI_FABRICATED_OPINION"
    E_AI_NETWORK_EGRESS = "E_AI_NETWORK_EGRESS"

    # --- UI (spec 30–39 ; gates A-10..A-13) ---
    E_UI_SPEC_DRIFT = "E_UI_SPEC_DRIFT"
    E_A11Y_REGRESSION = "E_A11Y_REGRESSION"
    E_VIEW_LAYOUT_SHIFT = "E_VIEW_LAYOUT_SHIFT"

    # --- Governance / acceptance (spec 46, 97, 99) ---
    E_SPEC_STALE_QUESTION = "E_SPEC_STALE_QUESTION"
    E_SPEC_DRIFT = "E_SPEC_DRIFT"
    E_ACCEPT_MALFORMED_GATE = "E_ACCEPT_MALFORMED_GATE"
    E_ACCEPT_UNPROVEN = "E_ACCEPT_UNPROVEN"

    # --- Bug family (spec 40 §1, §2, §7) ---
    E_BUG_UNTYPED_ERROR = "E_BUG_UNTYPED_ERROR"
    E_BUG_UNKNOWN_CODE = "E_BUG_UNKNOWN_CODE"
    E_BUG_ERROR_CHAIN_TOO_DEEP = "E_BUG_ERROR_CHAIN_TOO_DEEP"
    E_BUG_SILENT_SWALLOW = "E_BUG_SILENT_SWALLOW"
    E_BUG_TIER_LAUNDERING = "E_BUG_TIER_LAUNDERING"
    E_BUG_ENUM_ORPHAN = "E_BUG_ENUM_ORPHAN"
    E_BUG_DOUBLE_LOG = "E_BUG_DOUBLE_LOG"
    E_BUG_UNCORRELATED_LOG = "E_BUG_UNCORRELATED_LOG"


ALL_CODES: frozenset[str] = frozenset(c.value for c in ErrorCode)
