import { EditorRuleKindType, EditorToolFamilyType } from "@/lib/editor/types";

export enum InspectionCategoryType {
  PresenceAbsence = "Presence / Absence",
  FlawDetection = "Flaw Detection",
  CountMeasure = "Count & Measure",
  IdOcr = "ID / OCR",
  ColorCoating = "Color & Coating",
}

export interface ToolParamDescriptor {
  key: string;
  label: string;
  type: "number" | "text" | "select" | "boolean";
  unit?: string;
  min?: number;
  max?: number;
  step?: number;
  options?: { value: string; label: string }[];
  defaultValue: string | number | boolean;
  description: string;
}

export interface VisionToolDefinition {
  id: string;
  code: string;
  name: string;
  category: InspectionCategoryType;
  kind: EditorRuleKindType;
  family: EditorToolFamilyType;
  description: string;
  targetFeature: string;
  defaultExposureMs: number;
  defaultGainDb: number;
  defaultLightPct: number;
  defaultChannels: number[];
  defaultStrobeUs: number;
  params: ToolParamDescriptor[];
  defaultParamValues: Record<string, string | number | boolean | undefined>;
}

export const VISION_TOOL_CATALOG: readonly VisionToolDefinition[] = Object.freeze([
  // --- Category 1: Presence / Absence ---
  {
    id: "T102",
    code: "T102",
    name: "Greyscale Pattern Matching",
    category: InspectionCategoryType.PresenceAbsence,
    kind: EditorRuleKindType.C,
    family: EditorToolFamilyType.Rect,
    description: "2-bit greyscale constellation pattern matching with numbered white boxes to verify component presence, orientation, and laser marking.",
    targetFeature: "IC body orientation, pin 1 polarity, chip laser marking, connector latch seated state",
    defaultExposureMs: 12.5,
    defaultGainDb: 0.0,
    defaultLightPct: 85,
    defaultChannels: [1, 2],
    defaultStrobeUs: 350,
    defaultParamValues: {
      toolCode: "T102",
      greyscaleLevel: 170,
      minMatchPercent: 80,
      tolerancePx: 8,
      angleRangeDeg: 15,
      scoreMetric: "constellation",
      hasPolarityInverted: false,
    },
    params: [
      {
        key: "greyscaleLevel",
        label: "Greyscale Level (Threshold)",
        type: "number",
        min: 10,
        max: 250,
        step: 5,
        defaultValue: 170,
        description: "2-bit binarization threshold separating reflective pattern markings from substrate.",
      },
      {
        key: "minMatchPercent",
        label: "Min Match %",
        type: "number",
        unit: "%",
        min: 50,
        max: 100,
        step: 1,
        defaultValue: 80,
        description: "Minimum correlation / box match percentage required to declare inspection PASS.",
      },
      {
        key: "tolerancePx",
        label: "Position Tolerance",
        type: "number",
        unit: "px",
        min: 1,
        max: 50,
        step: 1,
        defaultValue: 8,
        description: "Allowable physical position deviation for detected pattern elements.",
      },
      {
        key: "activeBoxCount",
        label: "Reference Box Count",
        type: "number",
        min: 1,
        max: 64,
        step: 1,
        defaultValue: 24,
        description: "Number of white constellation boxes formulating the reference golden template.",
      },
      {
        key: "angleRangeDeg",
        label: "Search Angle Range",
        type: "select",
        unit: "deg",
        options: [
          { value: "0", label: "0° (Fixed)" },
          { value: "5", label: "±5° (Tight)" },
          { value: "15", label: "±15° (Standard SMT)" },
          { value: "45", label: "±45° (Wide)" },
          { value: "180", label: "±180° (Full 360°)" },
        ],
        defaultValue: "15",
        description: "Angular rotation tolerance search window.",
      },
      {
        key: "scoreMetric",
        label: "Matching Algorithm",
        type: "select",
        options: [
          { value: "constellation", label: "2-Bit Constellation Box Matching" },
          { value: "ncc", label: "Normalized Cross Correlation (NCC)" },
          { value: "edge", label: "Edge Gradient Correlation" },
        ],
        defaultValue: "constellation",
        description: "Core computer vision pattern matching and verification algorithm.",
      },
    ],
  },
  {
    id: "T105",
    code: "T105",
    name: "Pin 1 Orientation Config",
    category: InspectionCategoryType.PresenceAbsence,
    kind: EditorRuleKindType.C,
    family: EditorToolFamilyType.Rect,
    description: "Detects physical circular hole or laser polarity dimple on IC packages to guarantee correct orientation.",
    targetFeature: "Pin 1 polarity dimple, circular fiducial dot, chamfer notch",
    defaultExposureMs: 10.0,
    defaultGainDb: 0.0,
    defaultLightPct: 80,
    defaultChannels: [1, 2],
    defaultStrobeUs: 300,
    defaultParamValues: {
      toolCode: "T105",
      thresholdLuma: 75,
      tolerancePx: 25,
      expectedDiameterPx: 24,
      minCircularityPct: 75,
    },
    params: [
      {
        key: "thresholdLuma",
        label: "Luminance Threshold",
        type: "number",
        min: 20,
        max: 240,
        step: 5,
        defaultValue: 75,
        description: "Greyscale threshold separating Pin 1 dimple from IC body.",
      },
      {
        key: "expectedDiameterPx",
        label: "Expected Hole Diameter",
        type: "number",
        unit: "px",
        min: 5,
        max: 100,
        step: 1,
        defaultValue: 24,
        description: "Expected circular hole diameter in image pixels.",
      },
      {
        key: "minCircularityPct",
        label: "Min Circularity %",
        type: "number",
        unit: "%",
        min: 60,
        max: 100,
        step: 1,
        defaultValue: 75,
        description: "Roundness metric ensuring detected feature is a true circular dimple.",
      },
    ],
  },
  {
    id: "T101",
    code: "T101",
    name: "Area Gate (Pixel Intensity)",
    category: InspectionCategoryType.PresenceAbsence,
    kind: EditorRuleKindType.R,
    family: EditorToolFamilyType.Rect,
    description: "Calculates foreground pixel density to confirm solder fillet presence and passive placement.",
    targetFeature: "SMD 0402 / 0201 capacitors, resistors, solder paste deposits",
    defaultExposureMs: 8.0,
    defaultGainDb: 1.2,
    defaultLightPct: 90,
    defaultChannels: [1],
    defaultStrobeUs: 250,
    defaultParamValues: {
      toolCode: "T101",
      intensityThreshold: 128,
      minAreaPx: 4000,
      maxAreaPx: 30000,
      presencePolarity: "brightOnDark",
    },
    params: [
      {
        key: "intensityThreshold",
        label: "Intensity Threshold",
        type: "number",
        min: 0,
        max: 255,
        step: 1,
        defaultValue: 128,
        description: "Grayscale cutoff dividing foreground from substrate background.",
      },
      {
        key: "minAreaPx",
        label: "Min Pixel Area",
        type: "number",
        unit: "px",
        min: 1,
        max: 50000,
        step: 10,
        defaultValue: 50,
        description: "Minimum threshold pixels required for presence confirmation.",
      },
      {
        key: "presencePolarity",
        label: "Target Polarity",
        type: "select",
        options: [
          { value: "brightOnDark", label: "Bright on Dark (Solder / Silver pad)" },
          { value: "darkOnBright", label: "Dark on Bright (Black IC / Chip body)" },
        ],
        defaultValue: "brightOnDark",
        description: "Foreground contrast polarity relative to background.",
      },
    ],
  },
  {
    id: "T104",
    code: "T104",
    name: "Edge Count & Lead Presence",
    category: InspectionCategoryType.PresenceAbsence,
    kind: EditorRuleKindType.R,
    family: EditorToolFamilyType.Rect,
    description: "Counts spatial edge transitions along a linear profile to verify all IC leads are present.",
    targetFeature: "QFP / SOIC / Connector terminal lead count and bent pin detection",
    defaultExposureMs: 10.0,
    defaultGainDb: 0.5,
    defaultLightPct: 80,
    defaultChannels: [2, 3],
    defaultStrobeUs: 300,
    defaultParamValues: {
      toolCode: "T104",
      expectedCount: 16,
      minEdgeContrast: 35,
      scanDirection: "horizontal",
    },
    params: [
      {
        key: "expectedCount",
        label: "Expected Lead Count",
        type: "number",
        min: 1,
        max: 256,
        step: 1,
        defaultValue: 16,
        description: "Exact number of physical leads expected across the inspection line.",
      },
      {
        key: "minEdgeContrast",
        label: "Min Edge Contrast",
        type: "number",
        min: 5,
        max: 150,
        step: 5,
        defaultValue: 35,
        description: "Minimum grayscale gradient step to register a valid pin boundary.",
      },
    ],
  },

  // --- Category 2: Flaw Detection ---
  {
    id: "T109",
    code: "T109",
    name: "Binary Blob (Solder Bridge Detector)",
    category: InspectionCategoryType.FlawDetection,
    kind: EditorRuleKindType.K,
    family: EditorToolFamilyType.Rect,
    description: "Morphological connected component analysis detecting metallic bridges and solder shorts.",
    targetFeature: "Solder bridging between QFP / SOP leads, solder balls, tin whiskers",
    defaultExposureMs: 5.0,
    defaultGainDb: 2.0,
    defaultLightPct: 100,
    defaultChannels: [1, 3],
    defaultStrobeUs: 400,
    defaultParamValues: {
      toolCode: "T109",
      binarizeThreshold: 140,
      minDefectAreaPx: 15,
      maxAllowedDefects: 0,
      defectType: "solderBridge",
    },
    params: [
      {
        key: "binarizeThreshold",
        label: "Binarization Threshold",
        type: "number",
        min: 10,
        max: 250,
        step: 5,
        defaultValue: 140,
        description: "Threshold separating reflective solder bridges from PCB mask.",
      },
      {
        key: "minDefectAreaPx",
        label: "Min Defect Area",
        type: "number",
        unit: "px",
        min: 3,
        max: 1000,
        step: 1,
        defaultValue: 15,
        description: "Blob area in pixels required to trigger a bridge rejection.",
      },
      {
        key: "maxAllowedDefects",
        label: "Defect Acceptance Limit",
        type: "number",
        min: 0,
        max: 5,
        step: 1,
        defaultValue: 0,
        description: "Maximum allowable defects before flagging entire board as NG (0 = Zero Tolerance).",
      },
    ],
  },
  {
    id: "T108",
    code: "T108",
    name: "Void & Porosity Detector",
    category: InspectionCategoryType.FlawDetection,
    kind: EditorRuleKindType.K,
    family: EditorToolFamilyType.Rect,
    description: "Computes total area percentage of internal voids in thermal pads and solder ball joints.",
    targetFeature: "QFN ground pad solder voids, BGA ball porosity (IPC-A-610 standards)",
    defaultExposureMs: 7.5,
    defaultGainDb: 1.0,
    defaultLightPct: 95,
    defaultChannels: [1, 2],
    defaultStrobeUs: 300,
    defaultParamValues: {
      toolCode: "T108",
      maxTotalVoidPct: 25,
      maxSingleVoidPct: 15,
      sensitivityMode: "standard",
    },
    params: [
      {
        key: "maxTotalVoidPct",
        label: "Max Total Void %",
        type: "number",
        unit: "%",
        min: 5,
        max: 50,
        step: 1,
        defaultValue: 25,
        description: "Maximum allowable cumulative void area per IPC-A-610 Class 3.",
      },
      {
        key: "maxSingleVoidPct",
        label: "Max Single Void %",
        type: "number",
        unit: "%",
        min: 3,
        max: 30,
        step: 1,
        defaultValue: 15,
        description: "Maximum allowable area for any single contiguous void bubble.",
      },
    ],
  },
  {
    id: "T107",
    code: "T107",
    name: "Scratch & Crack Detector",
    category: InspectionCategoryType.FlawDetection,
    kind: EditorRuleKindType.K,
    family: EditorToolFamilyType.Rect,
    description: "High-pass spatial frequency filtering detecting micro-cracks on silicon dies and mask scratches.",
    targetFeature: "Silicon die edge chips, surface scratch on passivation, PCB trace hair fractures",
    defaultExposureMs: 6.0,
    defaultGainDb: 2.5,
    defaultLightPct: 90,
    defaultChannels: [3, 4],
    defaultStrobeUs: 350,
    defaultParamValues: {
      toolCode: "T107",
      gradientThreshold: 45,
      minCrackLengthPx: 12,
      filterKernel: "sobel",
    },
    params: [
      {
        key: "gradientThreshold",
        label: "Edge Gradient Threshold",
        type: "number",
        min: 10,
        max: 150,
        step: 5,
        defaultValue: 45,
        description: "Derivative threshold for detecting abrupt surface elevation discontinuities.",
      },
      {
        key: "minCrackLengthPx",
        label: "Min Crack Length",
        type: "number",
        unit: "px",
        min: 5,
        max: 200,
        step: 1,
        defaultValue: 12,
        description: "Minimum contiguous crack length required to reject.",
      },
    ],
  },

  // --- Category 3: Count & Measure ---
  {
    id: "T110",
    code: "T110",
    name: "Caliper & Edge (Lead Pitch / Width)",
    category: InspectionCategoryType.CountMeasure,
    kind: EditorRuleKindType.E,
    family: EditorToolFamilyType.Rect,
    description: "Sub-pixel metrology measuring pin pitch, terminal width, and co-planarity alignment.",
    targetFeature: "QFP / SOIC terminal pitch (e.g. 0.50mm / 0.65mm), lead width, tip straightness",
    defaultExposureMs: 10.0,
    defaultGainDb: 0.0,
    defaultLightPct: 75,
    defaultChannels: [2, 4],
    defaultStrobeUs: 300,
    defaultParamValues: {
      toolCode: "T110",
      nominalDimensionMm: 0.50,
      lowerToleranceMm: -0.05,
      upperToleranceMm: 0.05,
      edgeTransition: "any",
      measurementAxis: "horizontal",
    },
    params: [
      {
        key: "nominalDimensionMm",
        label: "Nominal Dimension",
        type: "number",
        unit: "mm",
        min: 0.01,
        max: 50.0,
        step: 0.01,
        defaultValue: 0.50,
        description: "Target design pitch or lead width from CAD drawing.",
      },
      {
        key: "lowerToleranceMm",
        label: "Lower Tolerance (-Tol)",
        type: "number",
        unit: "mm",
        min: -1.0,
        max: 0.0,
        step: 0.01,
        defaultValue: -0.05,
        description: "Maximum allowable negative dimensional deviation.",
      },
      {
        key: "upperToleranceMm",
        label: "Upper Tolerance (+Tol)",
        type: "number",
        unit: "mm",
        min: 0.0,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.05,
        description: "Maximum allowable positive dimensional deviation.",
      },
      {
        key: "measurementAxis",
        label: "Measurement Axis",
        type: "select",
        options: [
          { value: "horizontal", label: "Horizontal (X-Axis)" },
          { value: "vertical", label: "Vertical (Y-Axis)" },
        ],
        defaultValue: "horizontal",
        description: "Spatial orientation of caliper search lines.",
      },
    ],
  },
  {
    id: "T111",
    code: "T111",
    name: "Circle & Via Gauge",
    category: InspectionCategoryType.CountMeasure,
    kind: EditorRuleKindType.E,
    family: EditorToolFamilyType.Rect,
    description: "RANSAC circle fitting measuring drill hole diameter, via annular ring, and fiducial roundness.",
    targetFeature: "Mounting holes, plated through-holes (PTH), optical fiducial dots",
    defaultExposureMs: 9.0,
    defaultGainDb: 0.0,
    defaultLightPct: 80,
    defaultChannels: [1, 2],
    defaultStrobeUs: 280,
    defaultParamValues: {
      toolCode: "T111",
      nominalDiameterMm: 1.20,
      diameterToleranceMm: 0.08,
      minRoundnessScorePct: 85,
    },
    params: [
      {
        key: "nominalDiameterMm",
        label: "Nominal Diameter",
        type: "number",
        unit: "mm",
        min: 0.1,
        max: 20.0,
        step: 0.05,
        defaultValue: 1.20,
        description: "Nominal hole or circle diameter in millimeters.",
      },
      {
        key: "diameterToleranceMm",
        label: "Tolerance (±)",
        type: "number",
        unit: "mm",
        min: 0.01,
        max: 1.0,
        step: 0.01,
        defaultValue: 0.08,
        description: "Bilateral diameter tolerance margin.",
      },
    ],
  },

  // --- Category 4: ID / OCR ---
  {
    id: "T103",
    code: "T103",
    name: "2D DataMatrix & QR Code Reader",
    category: InspectionCategoryType.IdOcr,
    kind: EditorRuleKindType.E,
    family: EditorToolFamilyType.Rect,
    description: "Decodes laser-etched ECC200 DataMatrix, wafer 2D codes, and high-density PCB serial markers.",
    targetFeature: "PCB serial number DataMatrix, wafer identification code, package QR",
    defaultExposureMs: 15.0,
    defaultGainDb: 1.0,
    defaultLightPct: 80,
    defaultChannels: [1, 2],
    defaultStrobeUs: 350,
    defaultParamValues: {
      toolCode: "T103",
      symbology: "dataMatrix",
      expectedPatternRegex: "STM32.*",
      minQualityGrade: "B",
    },
    params: [
      {
        key: "symbology",
        label: "Symbology Type",
        type: "select",
        options: [
          { value: "dataMatrix", label: "ECC200 DataMatrix" },
          { value: "qrCode", label: "QR Code" },
          { value: "microQr", label: "Micro QR" },
        ],
        defaultValue: "dataMatrix",
        description: "2D barcode standard encoding scheme.",
      },
      {
        key: "expectedPatternRegex",
        label: "Expected Pattern (Regex)",
        type: "text",
        defaultValue: "STM32.*",
        description: "Regular expression verifying the decoded serial format matches expected lot format.",
      },
    ],
  },
  {
    id: "T106",
    code: "T106",
    name: "Laser Marking OCR",
    category: InspectionCategoryType.IdOcr,
    kind: EditorRuleKindType.S,
    family: EditorToolFamilyType.Rect,
    description: "Deep OCR character recognition reading laser-marked part numbers, lot codes, and date codes.",
    targetFeature: "Laser-etched IC top marking, silicon revision text (e.g. STM32F407VGT6)",
    defaultExposureMs: 14.0,
    defaultGainDb: 1.5,
    defaultLightPct: 85,
    defaultChannels: [2, 3],
    defaultStrobeUs: 320,
    defaultParamValues: {
      toolCode: "T106",
      expectedString: "STM32F4",
      fontType: "laserEtched",
      minConfidencePct: 80,
    },
    params: [
      {
        key: "expectedString",
        label: "Expected Text / Prefix",
        type: "text",
        defaultValue: "STM32F4",
        description: "Expected text string required to pass inspection.",
      },
      {
        key: "minConfidencePct",
        label: "Min Confidence",
        type: "number",
        unit: "%",
        min: 50,
        max: 99,
        step: 1,
        defaultValue: 80,
        description: "Minimum neural OCR confidence per character.",
      },
    ],
  },

  // --- Category 5: Color & Coating ---
  {
    id: "T112",
    code: "T112",
    name: "Conformal Coating UV Fluorescence",
    category: InspectionCategoryType.ColorCoating,
    kind: EditorRuleKindType.R,
    family: EditorToolFamilyType.Rect,
    description: "Evaluates UV fluorescent tracer dye illumination to verify complete conformal coating coverage.",
    targetFeature: "Silicone / Acrylic conformal coating coverage, shadow area voids, edge wet-out",
    defaultExposureMs: 25.0,
    defaultGainDb: 3.0,
    defaultLightPct: 100,
    defaultChannels: [1, 2, 3, 4],
    defaultStrobeUs: 500,
    defaultParamValues: {
      toolCode: "T112",
      minCoveragePct: 95,
      fluorescenceThreshold: 110,
      uvColorChannel: "uvBlue",
    },
    params: [
      {
        key: "minCoveragePct",
        label: "Min Coverage %",
        type: "number",
        unit: "%",
        min: 80,
        max: 100,
        step: 1,
        defaultValue: 95,
        description: "Percentage of target surface area that must emit UV fluorescence.",
      },
      {
        key: "fluorescenceThreshold",
        label: "UV Glow Threshold",
        type: "number",
        min: 30,
        max: 230,
        step: 5,
        defaultValue: 110,
        description: "Intensity threshold identifying coated vs uncoated bare substrate.",
      },
    ],
  },
]);

export function getVisionToolsByCategory(category: InspectionCategoryType): VisionToolDefinition[] {
  return VISION_TOOL_CATALOG.filter((t) => t.category === category);
}

export function findVisionTool(id: string): VisionToolDefinition | undefined {
  return VISION_TOOL_CATALOG.find((t) => t.id === id || t.code === id);
}
