#!/usr/bin/env python3
"""Generate TypeScript types from IPC schema $defs.

Reads every ``spec/21-app/shell/schemas/ipc/*.schema.json`` and emits a
single ``src/generated/ipc-types.ts`` file. TS callers import from that
file so they cannot drift from ``$defs``.

Supported JSON-Schema subset (same as ``check-ipc-examples.py``):
type (string|list), required, properties, additionalProperties (bool),
items, enum, const, minimum/maximum, ``$ref`` to ``#/$defs/<name>``.

CI drift check: run this script and fail if ``git diff --exit-code``
reports changes under ``src/generated/``.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / "spec" / "21-app" / "shell" / "schemas" / "ipc"
OUT_FILE = ROOT / "src" / "generated" / "ipc-types.ts"

REF_RE = re.compile(r"^#/\$defs/(?P<name>[a-zA-Z0-9_.-]+)$")


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[._-]+", name) if part)


def ts_name(group: str, def_name: str) -> str:
    """Namespace every def by its schema group so cross-file names never collide.

    Method-shaped defs (``<group>.<method>.<kind>``) keep the natural PascalCase.
    Local helpers get a ``Local`` marker to keep them distinct from
    coincidentally-similar method names in the same group.
    """
    if def_name.startswith(group + "."):
        return pascal(def_name)
    return pascal(f"{group}.local.{def_name}")


def render(schema: dict, group: str, defs: set[str], indent: int = 0) -> str:
    pad = "  " * indent
    if "$ref" in schema:
        m = REF_RE.match(schema["$ref"])
        if not m or m.group("name") not in defs:
            raise SystemExit(f"unknown $ref: {schema['$ref']}")
        return ts_name(group, m.group("name"))
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    t = schema.get("type")
    if isinstance(t, list):
        return " | ".join(render({**schema, "type": tt}, group, defs, indent) for tt in t)
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        item = schema.get("items", {})
        return f"Array<{render(item, group, defs, indent)}>"
    if t == "object" or "properties" in schema or "required" in schema:
        props = schema.get("properties") or {}
        required = set(schema.get("required") or [])
        additional = schema.get("additionalProperties", True)
        if not props and additional is False:
            return "Record<string, never>"
        if not props:
            return "Record<string, unknown>"
        lines = ["{"]
        for key, value in props.items():
            opt = "" if key in required else "?"
            safe = key if re.match(r"^[A-Za-z_$][A-Za-z0-9_$]*$", key) else json.dumps(key)
            lines.append(f"{pad}  {safe}{opt}: {render(value, group, defs, indent + 1)};")
        if additional is not False:
            lines.append(f"{pad}  [key: string]: unknown;")
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    return "unknown"


def method_from_def(def_name: str) -> tuple[str, str] | None:
    """Split ``group.method.req|res|stream`` into (``group.method``, kind)."""
    parts = def_name.rsplit(".", 1)
    if len(parts) != 2 or parts[1] not in {"req", "res", "stream"}:
        return None
    return parts[0], parts[1]


def main() -> int:
    schemas = sorted(SCHEMA_DIR.glob("*.schema.json"))
    if not schemas:
        print(f"no schemas found under {SCHEMA_DIR}", file=sys.stderr)
        return 1

    # Group -> {def_name: schema}. Refs resolve within the same group.
    per_group: dict[str, dict[str, dict[str, Any]]] = {}
    for path in schemas:
        group = path.name.split(".schema.json")[0]
        data = json.loads(path.read_text(encoding="utf-8"))
        per_group[group] = dict(data.get("$defs") or {})

    lines: list[str] = [
        "// AUTO-GENERATED by linter-scripts/generate-ipc-types.py",
        "// DO NOT EDIT. Run the generator after changing any $defs entry.",
        "// Source: spec/21-app/shell/schemas/ipc/*.schema.json",
        "",
    ]

    method_map: dict[str, dict[str, str]] = {}
    for group in sorted(per_group):
        defs_map = per_group[group]
        def_names = set(defs_map)
        for name in sorted(defs_map):
            body = render(defs_map[name], group, def_names)
            tsn = ts_name(group, name)
            lines.append(f"export type {tsn} = {body};")
            lines.append("")
            parsed = method_from_def(name)
            if parsed:
                method, kind = parsed
                method_map.setdefault(method, {})[kind] = tsn

    if method_map:
        lines.append("export interface IpcMap {")
        for method in sorted(method_map):
            kinds = method_map[method]
            entries = "; ".join(f"{k}: {v}" for k, v in sorted(kinds.items()))
            safe_method = method if re.match(r"^[A-Za-z_$][A-Za-z0-9_$]*$", method) else json.dumps(method)
            lines.append(f'  {safe_method}: {{ {entries} }};')
        lines.append("}")
        lines.append("")
        lines.append("export type IpcMethod = keyof IpcMap;")
        lines.append("")

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    total = sum(len(v) for v in per_group.values())
    print(f"wrote {OUT_FILE.relative_to(ROOT)} ({total} types, {len(method_map)} methods)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
