export enum AppRouteType {
  Home = "/",
  Setup = "/setup",
  SetupRules = "/setup/rules",
  SetupRoi = "/setup/roi",
  SetupReference = "/setup/reference",
  Settings = "/settings",
  SettingsCamera = "/settings/camera",
  SettingsTrigger = "/settings/trigger",
  SettingsLighting = "/settings/lighting",
  SettingsShortcuts = "/settings/shortcuts",
  SettingsLicense = "/settings/license",
  Projects = "/projects",
  Run = "/run",
  Results = "/results",
  Errors = "/errors",
  Diagnostics = "/diagnostics",
  Ops = "/ops",
  AiTesting = "/ai-testing",
  CliSessions = "/cli/sessions",
  TrialRun = "/trial-run",
}
