/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrialRunRouteImport } from './routes/trial-run'
import { Route as ShortcutsRouteImport } from './routes/shortcuts'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunRouteImport } from './routes/run'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as CliRouteImport } from './routes/cli'
import { Route as AiTestingRouteImport } from './routes/ai-testing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as CliIndexRouteImport } from './routes/cli.index'
import { Route as CliSessionsIndexRouteImport } from './routes/cli-sessions.index'
import { Route as SetupRulesRouteImport } from './routes/setup.rules'
import { Route as SetupRoiRouteImport } from './routes/setup.roi'
import { Route as SetupReferenceRouteImport } from './routes/setup.reference'
import { Route as SetupFunctionsRouteImport } from './routes/setup.functions'
import { Route as SetupChainEventsRouteImport } from './routes/setup.chain-events'
import { Route as SetupCategoriesRouteImport } from './routes/setup.categories'
import { Route as SetupCameraRouteImport } from './routes/setup.camera'
import { Route as SettingsTriggerRouteImport } from './routes/settings.trigger'
import { Route as SettingsShortcutsRouteImport } from './routes/settings.shortcuts'
import { Route as SettingsLightingRouteImport } from './routes/settings.lighting'
import { Route as SettingsLicenseRouteImport } from './routes/settings.license'
import { Route as SettingsCameraRouteImport } from './routes/settings.camera'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ObservabilitySessionsRouteImport } from './routes/observability.sessions'
import { Route as CliSettingsRouteImport } from './routes/cli.settings'
import { Route as CliSessionsRouteImport } from './routes/cli.sessions'
import { Route as CliSamplesRouteImport } from './routes/cli.samples'
import { Route as CliRulesRouteImport } from './routes/cli.rules'
import { Route as CliIpcRouteImport } from './routes/cli.ipc'
import { Route as CliSessionsRunIdRouteImport } from './routes/cli-sessions.$runId'
import { Route as SetupCategoriesIndexRouteImport } from './routes/setup.categories.index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as SetupRulesIdRouteImport } from './routes/setup.rules.$id'
import { Route as SetupCategoriesIdRouteImport } from './routes/setup.categories.$id'
import { Route as ProjectsProjectIdTrialRunRouteImport } from './routes/projects.$projectId.trial-run'
import { Route as ProjectsProjectIdRunsRouteImport } from './routes/projects.$projectId.runs'
import { Route as ProjectsProjectIdRulesetsRouteImport } from './routes/projects.$projectId.rulesets'
import { Route as ProjectsProjectIdCategoriesRouteImport } from './routes/projects.$projectId.categories'
import { Route as ProjectsProjectIdCameraRouteImport } from './routes/projects.$projectId.camera'
import { Route as ProjectsProjectIdAiTestingHistoryRouteImport } from './routes/projects.$projectId.ai-testing-history'
import { Route as ProjectsProjectIdAiTestingRouteImport } from './routes/projects.$projectId.ai-testing'
import { Route as ObservabilityRunsRunIdRouteImport } from './routes/observability.runs.$runId'
import { Route as CliSessionsCompareRouteImport } from './routes/cli.sessions.compare'
import { Route as CliSessionsSessionIdRouteImport } from './routes/cli.sessions.$sessionId'
import { Route as CliSamplesSampleIdRouteImport } from './routes/cli.samples.$sampleId'
import { Route as CliRulesImportRouteImport } from './routes/cli.rules.import'
import { Route as CliRulesRuleIdRouteImport } from './routes/cli.rules.$ruleId'
import { Route as ApiCameraDefaultsRouteImport } from './routes/api/camera.defaults'
import { Route as ApiCameraCaptureRouteImport } from './routes/api/camera.capture'
import { Route as AdminSecurityDenialBurstRouteImport } from './routes/admin.security.denial-burst'
import { Route as AdminDebugCalibrationDistributionsRouteImport } from './routes/admin.debug.calibration-distributions'
import { Route as AdminDebugCalibrationRouteImport } from './routes/admin.debug.calibration'
import { Route as ProjectsProjectIdRulesetsIndexRouteImport } from './routes/projects.$projectId.rulesets.index'
import { Route as ProjectsProjectIdTrialRunRunIdRouteImport } from './routes/projects.$projectId.trial-run.$runId'
import { Route as ProjectsProjectIdRulesetsNewRouteImport } from './routes/projects.$projectId.rulesets.new'
import { Route as ProjectsProjectIdRulesetsRulesetIdRouteImport } from './routes/projects.$projectId.rulesets.$rulesetId'
import { Route as ObservabilitySessionsCliInvocationIdLogsRouteImport } from './routes/observability.sessions.$cliInvocationId.logs'
import { Route as ObservabilitySessionsCliInvocationIdIpcRouteImport } from './routes/observability.sessions.$cliInvocationId.ipc'
import { Route as ApiPublicHooksAuditRetentionRouteImport } from './routes/api/public/hooks/audit-retention'
import { Route as ApiPublicHealthReadyRouteImport } from './routes/api/public/health.ready'
import { Route as ApiPublicHealthLiveRouteImport } from './routes/api/public/health.live'
import { Route as ApiCliSessionsRunIdLogRouteImport } from './routes/api/cli.sessions.$runId.log'
import { Route as ApiCliSessionsRunIdExportRouteImport } from './routes/api/cli.sessions.$runId.export'
import { Route as ApiCliIpcMsgIdRequeueRouteImport } from './routes/api/cli.ipc.$msgId.requeue'
import { Route as ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRouteImport } from './routes/projects.$projectId.rulesets.$rulesetId.rules.$ruleId'

const TrialRunRoute = TrialRunRouteImport.update({
  id: '/trial-run',
  path: '/trial-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcutsRoute = ShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTestingRoute = AiTestingRouteImport.update({
  id: '/ai-testing',
  path: '/ai-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const CliIndexRoute = CliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CliRoute,
} as any)
const CliSessionsIndexRoute = CliSessionsIndexRouteImport.update({
  id: '/cli-sessions/',
  path: '/cli-sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRulesRoute = SetupRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SetupRoute,
} as any)
const SetupRoiRoute = SetupRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => SetupRoute,
} as any)
const SetupReferenceRoute = SetupReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => SetupRoute,
} as any)
const SetupFunctionsRoute = SetupFunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => SetupRoute,
} as any)
const SetupChainEventsRoute = SetupChainEventsRouteImport.update({
  id: '/chain-events',
  path: '/chain-events',
  getParentRoute: () => SetupRoute,
} as any)
const SetupCategoriesRoute = SetupCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SetupRoute,
} as any)
const SetupCameraRoute = SetupCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => SetupRoute,
} as any)
const SettingsTriggerRoute = SettingsTriggerRouteImport.update({
  id: '/trigger',
  path: '/trigger',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLightingRoute = SettingsLightingRouteImport.update({
  id: '/lighting',
  path: '/lighting',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLicenseRoute = SettingsLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCameraRoute = SettingsCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ObservabilitySessionsRoute = ObservabilitySessionsRouteImport.update({
  id: '/observability/sessions',
  path: '/observability/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const CliSettingsRoute = CliSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CliRoute,
} as any)
const CliSessionsRoute = CliSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => CliRoute,
} as any)
const CliSamplesRoute = CliSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => CliRoute,
} as any)
const CliRulesRoute = CliRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => CliRoute,
} as any)
const CliIpcRoute = CliIpcRouteImport.update({
  id: '/ipc',
  path: '/ipc',
  getParentRoute: () => CliRoute,
} as any)
const CliSessionsRunIdRoute = CliSessionsRunIdRouteImport.update({
  id: '/cli-sessions/$runId',
  path: '/cli-sessions/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupCategoriesIndexRoute = SetupCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupCategoriesRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const SetupRulesIdRoute = SetupRulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SetupRulesRoute,
} as any)
const SetupCategoriesIdRoute = SetupCategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SetupCategoriesRoute,
} as any)
const ProjectsProjectIdTrialRunRoute =
  ProjectsProjectIdTrialRunRouteImport.update({
    id: '/trial-run',
    path: '/trial-run',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRunsRoute = ProjectsProjectIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdRulesetsRoute =
  ProjectsProjectIdRulesetsRouteImport.update({
    id: '/rulesets',
    path: '/rulesets',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCategoriesRoute =
  ProjectsProjectIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCameraRoute = ProjectsProjectIdCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdAiTestingHistoryRoute =
  ProjectsProjectIdAiTestingHistoryRouteImport.update({
    id: '/ai-testing-history',
    path: '/ai-testing-history',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdAiTestingRoute =
  ProjectsProjectIdAiTestingRouteImport.update({
    id: '/ai-testing',
    path: '/ai-testing',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ObservabilityRunsRunIdRoute = ObservabilityRunsRunIdRouteImport.update({
  id: '/observability/runs/$runId',
  path: '/observability/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const CliSessionsCompareRoute = CliSessionsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => CliSessionsRoute,
} as any)
const CliSessionsSessionIdRoute = CliSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => CliSessionsRoute,
} as any)
const CliSamplesSampleIdRoute = CliSamplesSampleIdRouteImport.update({
  id: '/$sampleId',
  path: '/$sampleId',
  getParentRoute: () => CliSamplesRoute,
} as any)
const CliRulesImportRoute = CliRulesImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => CliRulesRoute,
} as any)
const CliRulesRuleIdRoute = CliRulesRuleIdRouteImport.update({
  id: '/$ruleId',
  path: '/$ruleId',
  getParentRoute: () => CliRulesRoute,
} as any)
const ApiCameraDefaultsRoute = ApiCameraDefaultsRouteImport.update({
  id: '/api/camera/defaults',
  path: '/api/camera/defaults',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCameraCaptureRoute = ApiCameraCaptureRouteImport.update({
  id: '/api/camera/capture',
  path: '/api/camera/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityDenialBurstRoute =
  AdminSecurityDenialBurstRouteImport.update({
    id: '/admin/security/denial-burst',
    path: '/admin/security/denial-burst',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDebugCalibrationDistributionsRoute =
  AdminDebugCalibrationDistributionsRouteImport.update({
    id: '/admin/debug/calibration-distributions',
    path: '/admin/debug/calibration-distributions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDebugCalibrationRoute = AdminDebugCalibrationRouteImport.update({
  id: '/admin/debug/calibration',
  path: '/admin/debug/calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRulesetsIndexRoute =
  ProjectsProjectIdRulesetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdRulesetsRoute,
  } as any)
const ProjectsProjectIdTrialRunRunIdRoute =
  ProjectsProjectIdTrialRunRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => ProjectsProjectIdTrialRunRoute,
  } as any)
const ProjectsProjectIdRulesetsNewRoute =
  ProjectsProjectIdRulesetsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProjectsProjectIdRulesetsRoute,
  } as any)
const ProjectsProjectIdRulesetsRulesetIdRoute =
  ProjectsProjectIdRulesetsRulesetIdRouteImport.update({
    id: '/$rulesetId',
    path: '/$rulesetId',
    getParentRoute: () => ProjectsProjectIdRulesetsRoute,
  } as any)
const ObservabilitySessionsCliInvocationIdLogsRoute =
  ObservabilitySessionsCliInvocationIdLogsRouteImport.update({
    id: '/$cliInvocationId/logs',
    path: '/$cliInvocationId/logs',
    getParentRoute: () => ObservabilitySessionsRoute,
  } as any)
const ObservabilitySessionsCliInvocationIdIpcRoute =
  ObservabilitySessionsCliInvocationIdIpcRouteImport.update({
    id: '/$cliInvocationId/ipc',
    path: '/$cliInvocationId/ipc',
    getParentRoute: () => ObservabilitySessionsRoute,
  } as any)
const ApiPublicHooksAuditRetentionRoute =
  ApiPublicHooksAuditRetentionRouteImport.update({
    id: '/api/public/hooks/audit-retention',
    path: '/api/public/hooks/audit-retention',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthReadyRoute = ApiPublicHealthReadyRouteImport.update({
  id: '/api/public/health/ready',
  path: '/api/public/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthLiveRoute = ApiPublicHealthLiveRouteImport.update({
  id: '/api/public/health/live',
  path: '/api/public/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliSessionsRunIdLogRoute = ApiCliSessionsRunIdLogRouteImport.update({
  id: '/api/cli/sessions/$runId/log',
  path: '/api/cli/sessions/$runId/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliSessionsRunIdExportRoute =
  ApiCliSessionsRunIdExportRouteImport.update({
    id: '/api/cli/sessions/$runId/export',
    path: '/api/cli/sessions/$runId/export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCliIpcMsgIdRequeueRoute = ApiCliIpcMsgIdRequeueRouteImport.update({
  id: '/api/cli/ipc/$msgId/requeue',
  path: '/api/cli/ipc/$msgId/requeue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRoute =
  ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRouteImport.update({
    id: '/rules/$ruleId',
    path: '/rules/$ruleId',
    getParentRoute: () => ProjectsProjectIdRulesetsRulesetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-testing': typeof AiTestingRoute
  '/cli': typeof CliRouteWithChildren
  '/diagnostics': typeof DiagnosticsRoute
  '/errors': typeof ErrorsRoute
  '/ops': typeof OpsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/results': typeof ResultsRoute
  '/run': typeof RunRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRouteWithChildren
  '/shortcuts': typeof ShortcutsRoute
  '/trial-run': typeof TrialRunRoute
  '/cli-sessions/$runId': typeof CliSessionsRunIdRoute
  '/cli/ipc': typeof CliIpcRoute
  '/cli/rules': typeof CliRulesRouteWithChildren
  '/cli/samples': typeof CliSamplesRouteWithChildren
  '/cli/sessions': typeof CliSessionsRouteWithChildren
  '/cli/settings': typeof CliSettingsRoute
  '/observability/sessions': typeof ObservabilitySessionsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/settings/camera': typeof SettingsCameraRoute
  '/settings/license': typeof SettingsLicenseRoute
  '/settings/lighting': typeof SettingsLightingRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/trigger': typeof SettingsTriggerRoute
  '/setup/camera': typeof SetupCameraRoute
  '/setup/categories': typeof SetupCategoriesRouteWithChildren
  '/setup/chain-events': typeof SetupChainEventsRoute
  '/setup/functions': typeof SetupFunctionsRoute
  '/setup/reference': typeof SetupReferenceRoute
  '/setup/roi': typeof SetupRoiRoute
  '/setup/rules': typeof SetupRulesRouteWithChildren
  '/cli-sessions/': typeof CliSessionsIndexRoute
  '/cli/': typeof CliIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/admin/debug/calibration': typeof AdminDebugCalibrationRoute
  '/admin/debug/calibration-distributions': typeof AdminDebugCalibrationDistributionsRoute
  '/admin/security/denial-burst': typeof AdminSecurityDenialBurstRoute
  '/api/camera/capture': typeof ApiCameraCaptureRoute
  '/api/camera/defaults': typeof ApiCameraDefaultsRoute
  '/cli/rules/$ruleId': typeof CliRulesRuleIdRoute
  '/cli/rules/import': typeof CliRulesImportRoute
  '/cli/samples/$sampleId': typeof CliSamplesSampleIdRoute
  '/cli/sessions/$sessionId': typeof CliSessionsSessionIdRoute
  '/cli/sessions/compare': typeof CliSessionsCompareRoute
  '/observability/runs/$runId': typeof ObservabilityRunsRunIdRoute
  '/projects/$projectId/ai-testing': typeof ProjectsProjectIdAiTestingRoute
  '/projects/$projectId/ai-testing-history': typeof ProjectsProjectIdAiTestingHistoryRoute
  '/projects/$projectId/camera': typeof ProjectsProjectIdCameraRoute
  '/projects/$projectId/categories': typeof ProjectsProjectIdCategoriesRoute
  '/projects/$projectId/rulesets': typeof ProjectsProjectIdRulesetsRouteWithChildren
  '/projects/$projectId/runs': typeof ProjectsProjectIdRunsRoute
  '/projects/$projectId/trial-run': typeof ProjectsProjectIdTrialRunRouteWithChildren
  '/setup/categories/$id': typeof SetupCategoriesIdRoute
  '/setup/rules/$id': typeof SetupRulesIdRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/setup/categories/': typeof SetupCategoriesIndexRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/hooks/audit-retention': typeof ApiPublicHooksAuditRetentionRoute
  '/observability/sessions/$cliInvocationId/ipc': typeof ObservabilitySessionsCliInvocationIdIpcRoute
  '/observability/sessions/$cliInvocationId/logs': typeof ObservabilitySessionsCliInvocationIdLogsRoute
  '/projects/$projectId/rulesets/$rulesetId': typeof ProjectsProjectIdRulesetsRulesetIdRouteWithChildren
  '/projects/$projectId/rulesets/new': typeof ProjectsProjectIdRulesetsNewRoute
  '/projects/$projectId/trial-run/$runId': typeof ProjectsProjectIdTrialRunRunIdRoute
  '/projects/$projectId/rulesets/': typeof ProjectsProjectIdRulesetsIndexRoute
  '/api/cli/ipc/$msgId/requeue': typeof ApiCliIpcMsgIdRequeueRoute
  '/api/cli/sessions/$runId/export': typeof ApiCliSessionsRunIdExportRoute
  '/api/cli/sessions/$runId/log': typeof ApiCliSessionsRunIdLogRoute
  '/projects/$projectId/rulesets/$rulesetId/rules/$ruleId': typeof ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-testing': typeof AiTestingRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/errors': typeof ErrorsRoute
  '/ops': typeof OpsRoute
  '/results': typeof ResultsRoute
  '/run': typeof RunRoute
  '/shortcuts': typeof ShortcutsRoute
  '/trial-run': typeof TrialRunRoute
  '/cli-sessions/$runId': typeof CliSessionsRunIdRoute
  '/cli/ipc': typeof CliIpcRoute
  '/cli/rules': typeof CliRulesRouteWithChildren
  '/cli/samples': typeof CliSamplesRouteWithChildren
  '/cli/sessions': typeof CliSessionsRouteWithChildren
  '/cli/settings': typeof CliSettingsRoute
  '/observability/sessions': typeof ObservabilitySessionsRouteWithChildren
  '/settings/camera': typeof SettingsCameraRoute
  '/settings/license': typeof SettingsLicenseRoute
  '/settings/lighting': typeof SettingsLightingRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/trigger': typeof SettingsTriggerRoute
  '/setup/camera': typeof SetupCameraRoute
  '/setup/chain-events': typeof SetupChainEventsRoute
  '/setup/functions': typeof SetupFunctionsRoute
  '/setup/reference': typeof SetupReferenceRoute
  '/setup/roi': typeof SetupRoiRoute
  '/setup/rules': typeof SetupRulesRouteWithChildren
  '/cli-sessions': typeof CliSessionsIndexRoute
  '/cli': typeof CliIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/setup': typeof SetupIndexRoute
  '/admin/debug/calibration': typeof AdminDebugCalibrationRoute
  '/admin/debug/calibration-distributions': typeof AdminDebugCalibrationDistributionsRoute
  '/admin/security/denial-burst': typeof AdminSecurityDenialBurstRoute
  '/api/camera/capture': typeof ApiCameraCaptureRoute
  '/api/camera/defaults': typeof ApiCameraDefaultsRoute
  '/cli/rules/$ruleId': typeof CliRulesRuleIdRoute
  '/cli/rules/import': typeof CliRulesImportRoute
  '/cli/samples/$sampleId': typeof CliSamplesSampleIdRoute
  '/cli/sessions/$sessionId': typeof CliSessionsSessionIdRoute
  '/cli/sessions/compare': typeof CliSessionsCompareRoute
  '/observability/runs/$runId': typeof ObservabilityRunsRunIdRoute
  '/projects/$projectId/ai-testing': typeof ProjectsProjectIdAiTestingRoute
  '/projects/$projectId/ai-testing-history': typeof ProjectsProjectIdAiTestingHistoryRoute
  '/projects/$projectId/camera': typeof ProjectsProjectIdCameraRoute
  '/projects/$projectId/categories': typeof ProjectsProjectIdCategoriesRoute
  '/projects/$projectId/runs': typeof ProjectsProjectIdRunsRoute
  '/projects/$projectId/trial-run': typeof ProjectsProjectIdTrialRunRouteWithChildren
  '/setup/categories/$id': typeof SetupCategoriesIdRoute
  '/setup/rules/$id': typeof SetupRulesIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/setup/categories': typeof SetupCategoriesIndexRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/hooks/audit-retention': typeof ApiPublicHooksAuditRetentionRoute
  '/observability/sessions/$cliInvocationId/ipc': typeof ObservabilitySessionsCliInvocationIdIpcRoute
  '/observability/sessions/$cliInvocationId/logs': typeof ObservabilitySessionsCliInvocationIdLogsRoute
  '/projects/$projectId/rulesets/$rulesetId': typeof ProjectsProjectIdRulesetsRulesetIdRouteWithChildren
  '/projects/$projectId/rulesets/new': typeof ProjectsProjectIdRulesetsNewRoute
  '/projects/$projectId/trial-run/$runId': typeof ProjectsProjectIdTrialRunRunIdRoute
  '/projects/$projectId/rulesets': typeof ProjectsProjectIdRulesetsIndexRoute
  '/api/cli/ipc/$msgId/requeue': typeof ApiCliIpcMsgIdRequeueRoute
  '/api/cli/sessions/$runId/export': typeof ApiCliSessionsRunIdExportRoute
  '/api/cli/sessions/$runId/log': typeof ApiCliSessionsRunIdLogRoute
  '/projects/$projectId/rulesets/$rulesetId/rules/$ruleId': typeof ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-testing': typeof AiTestingRoute
  '/cli': typeof CliRouteWithChildren
  '/diagnostics': typeof DiagnosticsRoute
  '/errors': typeof ErrorsRoute
  '/ops': typeof OpsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/results': typeof ResultsRoute
  '/run': typeof RunRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRouteWithChildren
  '/shortcuts': typeof ShortcutsRoute
  '/trial-run': typeof TrialRunRoute
  '/cli-sessions/$runId': typeof CliSessionsRunIdRoute
  '/cli/ipc': typeof CliIpcRoute
  '/cli/rules': typeof CliRulesRouteWithChildren
  '/cli/samples': typeof CliSamplesRouteWithChildren
  '/cli/sessions': typeof CliSessionsRouteWithChildren
  '/cli/settings': typeof CliSettingsRoute
  '/observability/sessions': typeof ObservabilitySessionsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/settings/camera': typeof SettingsCameraRoute
  '/settings/license': typeof SettingsLicenseRoute
  '/settings/lighting': typeof SettingsLightingRoute
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/settings/trigger': typeof SettingsTriggerRoute
  '/setup/camera': typeof SetupCameraRoute
  '/setup/categories': typeof SetupCategoriesRouteWithChildren
  '/setup/chain-events': typeof SetupChainEventsRoute
  '/setup/functions': typeof SetupFunctionsRoute
  '/setup/reference': typeof SetupReferenceRoute
  '/setup/roi': typeof SetupRoiRoute
  '/setup/rules': typeof SetupRulesRouteWithChildren
  '/cli-sessions/': typeof CliSessionsIndexRoute
  '/cli/': typeof CliIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/admin/debug/calibration': typeof AdminDebugCalibrationRoute
  '/admin/debug/calibration-distributions': typeof AdminDebugCalibrationDistributionsRoute
  '/admin/security/denial-burst': typeof AdminSecurityDenialBurstRoute
  '/api/camera/capture': typeof ApiCameraCaptureRoute
  '/api/camera/defaults': typeof ApiCameraDefaultsRoute
  '/cli/rules/$ruleId': typeof CliRulesRuleIdRoute
  '/cli/rules/import': typeof CliRulesImportRoute
  '/cli/samples/$sampleId': typeof CliSamplesSampleIdRoute
  '/cli/sessions/$sessionId': typeof CliSessionsSessionIdRoute
  '/cli/sessions/compare': typeof CliSessionsCompareRoute
  '/observability/runs/$runId': typeof ObservabilityRunsRunIdRoute
  '/projects/$projectId/ai-testing': typeof ProjectsProjectIdAiTestingRoute
  '/projects/$projectId/ai-testing-history': typeof ProjectsProjectIdAiTestingHistoryRoute
  '/projects/$projectId/camera': typeof ProjectsProjectIdCameraRoute
  '/projects/$projectId/categories': typeof ProjectsProjectIdCategoriesRoute
  '/projects/$projectId/rulesets': typeof ProjectsProjectIdRulesetsRouteWithChildren
  '/projects/$projectId/runs': typeof ProjectsProjectIdRunsRoute
  '/projects/$projectId/trial-run': typeof ProjectsProjectIdTrialRunRouteWithChildren
  '/setup/categories/$id': typeof SetupCategoriesIdRoute
  '/setup/rules/$id': typeof SetupRulesIdRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/setup/categories/': typeof SetupCategoriesIndexRoute
  '/api/public/health/live': typeof ApiPublicHealthLiveRoute
  '/api/public/health/ready': typeof ApiPublicHealthReadyRoute
  '/api/public/hooks/audit-retention': typeof ApiPublicHooksAuditRetentionRoute
  '/observability/sessions/$cliInvocationId/ipc': typeof ObservabilitySessionsCliInvocationIdIpcRoute
  '/observability/sessions/$cliInvocationId/logs': typeof ObservabilitySessionsCliInvocationIdLogsRoute
  '/projects/$projectId/rulesets/$rulesetId': typeof ProjectsProjectIdRulesetsRulesetIdRouteWithChildren
  '/projects/$projectId/rulesets/new': typeof ProjectsProjectIdRulesetsNewRoute
  '/projects/$projectId/trial-run/$runId': typeof ProjectsProjectIdTrialRunRunIdRoute
  '/projects/$projectId/rulesets/': typeof ProjectsProjectIdRulesetsIndexRoute
  '/api/cli/ipc/$msgId/requeue': typeof ApiCliIpcMsgIdRequeueRoute
  '/api/cli/sessions/$runId/export': typeof ApiCliSessionsRunIdExportRoute
  '/api/cli/sessions/$runId/log': typeof ApiCliSessionsRunIdLogRoute
  '/projects/$projectId/rulesets/$rulesetId/rules/$ruleId': typeof ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-testing'
    | '/cli'
    | '/diagnostics'
    | '/errors'
    | '/ops'
    | '/projects'
    | '/results'
    | '/run'
    | '/settings'
    | '/setup'
    | '/shortcuts'
    | '/trial-run'
    | '/cli-sessions/$runId'
    | '/cli/ipc'
    | '/cli/rules'
    | '/cli/samples'
    | '/cli/sessions'
    | '/cli/settings'
    | '/observability/sessions'
    | '/projects/$projectId'
    | '/settings/camera'
    | '/settings/license'
    | '/settings/lighting'
    | '/settings/shortcuts'
    | '/settings/trigger'
    | '/setup/camera'
    | '/setup/categories'
    | '/setup/chain-events'
    | '/setup/functions'
    | '/setup/reference'
    | '/setup/roi'
    | '/setup/rules'
    | '/cli-sessions/'
    | '/cli/'
    | '/projects/'
    | '/settings/'
    | '/setup/'
    | '/admin/debug/calibration'
    | '/admin/debug/calibration-distributions'
    | '/admin/security/denial-burst'
    | '/api/camera/capture'
    | '/api/camera/defaults'
    | '/cli/rules/$ruleId'
    | '/cli/rules/import'
    | '/cli/samples/$sampleId'
    | '/cli/sessions/$sessionId'
    | '/cli/sessions/compare'
    | '/observability/runs/$runId'
    | '/projects/$projectId/ai-testing'
    | '/projects/$projectId/ai-testing-history'
    | '/projects/$projectId/camera'
    | '/projects/$projectId/categories'
    | '/projects/$projectId/rulesets'
    | '/projects/$projectId/runs'
    | '/projects/$projectId/trial-run'
    | '/setup/categories/$id'
    | '/setup/rules/$id'
    | '/projects/$projectId/'
    | '/setup/categories/'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/hooks/audit-retention'
    | '/observability/sessions/$cliInvocationId/ipc'
    | '/observability/sessions/$cliInvocationId/logs'
    | '/projects/$projectId/rulesets/$rulesetId'
    | '/projects/$projectId/rulesets/new'
    | '/projects/$projectId/trial-run/$runId'
    | '/projects/$projectId/rulesets/'
    | '/api/cli/ipc/$msgId/requeue'
    | '/api/cli/sessions/$runId/export'
    | '/api/cli/sessions/$runId/log'
    | '/projects/$projectId/rulesets/$rulesetId/rules/$ruleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-testing'
    | '/diagnostics'
    | '/errors'
    | '/ops'
    | '/results'
    | '/run'
    | '/shortcuts'
    | '/trial-run'
    | '/cli-sessions/$runId'
    | '/cli/ipc'
    | '/cli/rules'
    | '/cli/samples'
    | '/cli/sessions'
    | '/cli/settings'
    | '/observability/sessions'
    | '/settings/camera'
    | '/settings/license'
    | '/settings/lighting'
    | '/settings/shortcuts'
    | '/settings/trigger'
    | '/setup/camera'
    | '/setup/chain-events'
    | '/setup/functions'
    | '/setup/reference'
    | '/setup/roi'
    | '/setup/rules'
    | '/cli-sessions'
    | '/cli'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/admin/debug/calibration'
    | '/admin/debug/calibration-distributions'
    | '/admin/security/denial-burst'
    | '/api/camera/capture'
    | '/api/camera/defaults'
    | '/cli/rules/$ruleId'
    | '/cli/rules/import'
    | '/cli/samples/$sampleId'
    | '/cli/sessions/$sessionId'
    | '/cli/sessions/compare'
    | '/observability/runs/$runId'
    | '/projects/$projectId/ai-testing'
    | '/projects/$projectId/ai-testing-history'
    | '/projects/$projectId/camera'
    | '/projects/$projectId/categories'
    | '/projects/$projectId/runs'
    | '/projects/$projectId/trial-run'
    | '/setup/categories/$id'
    | '/setup/rules/$id'
    | '/projects/$projectId'
    | '/setup/categories'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/hooks/audit-retention'
    | '/observability/sessions/$cliInvocationId/ipc'
    | '/observability/sessions/$cliInvocationId/logs'
    | '/projects/$projectId/rulesets/$rulesetId'
    | '/projects/$projectId/rulesets/new'
    | '/projects/$projectId/trial-run/$runId'
    | '/projects/$projectId/rulesets'
    | '/api/cli/ipc/$msgId/requeue'
    | '/api/cli/sessions/$runId/export'
    | '/api/cli/sessions/$runId/log'
    | '/projects/$projectId/rulesets/$rulesetId/rules/$ruleId'
  id:
    | '__root__'
    | '/'
    | '/ai-testing'
    | '/cli'
    | '/diagnostics'
    | '/errors'
    | '/ops'
    | '/projects'
    | '/results'
    | '/run'
    | '/settings'
    | '/setup'
    | '/shortcuts'
    | '/trial-run'
    | '/cli-sessions/$runId'
    | '/cli/ipc'
    | '/cli/rules'
    | '/cli/samples'
    | '/cli/sessions'
    | '/cli/settings'
    | '/observability/sessions'
    | '/projects/$projectId'
    | '/settings/camera'
    | '/settings/license'
    | '/settings/lighting'
    | '/settings/shortcuts'
    | '/settings/trigger'
    | '/setup/camera'
    | '/setup/categories'
    | '/setup/chain-events'
    | '/setup/functions'
    | '/setup/reference'
    | '/setup/roi'
    | '/setup/rules'
    | '/cli-sessions/'
    | '/cli/'
    | '/projects/'
    | '/settings/'
    | '/setup/'
    | '/admin/debug/calibration'
    | '/admin/debug/calibration-distributions'
    | '/admin/security/denial-burst'
    | '/api/camera/capture'
    | '/api/camera/defaults'
    | '/cli/rules/$ruleId'
    | '/cli/rules/import'
    | '/cli/samples/$sampleId'
    | '/cli/sessions/$sessionId'
    | '/cli/sessions/compare'
    | '/observability/runs/$runId'
    | '/projects/$projectId/ai-testing'
    | '/projects/$projectId/ai-testing-history'
    | '/projects/$projectId/camera'
    | '/projects/$projectId/categories'
    | '/projects/$projectId/rulesets'
    | '/projects/$projectId/runs'
    | '/projects/$projectId/trial-run'
    | '/setup/categories/$id'
    | '/setup/rules/$id'
    | '/projects/$projectId/'
    | '/setup/categories/'
    | '/api/public/health/live'
    | '/api/public/health/ready'
    | '/api/public/hooks/audit-retention'
    | '/observability/sessions/$cliInvocationId/ipc'
    | '/observability/sessions/$cliInvocationId/logs'
    | '/projects/$projectId/rulesets/$rulesetId'
    | '/projects/$projectId/rulesets/new'
    | '/projects/$projectId/trial-run/$runId'
    | '/projects/$projectId/rulesets/'
    | '/api/cli/ipc/$msgId/requeue'
    | '/api/cli/sessions/$runId/export'
    | '/api/cli/sessions/$runId/log'
    | '/projects/$projectId/rulesets/$rulesetId/rules/$ruleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiTestingRoute: typeof AiTestingRoute
  CliRoute: typeof CliRouteWithChildren
  DiagnosticsRoute: typeof DiagnosticsRoute
  ErrorsRoute: typeof ErrorsRoute
  OpsRoute: typeof OpsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  RunRoute: typeof RunRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRouteWithChildren
  ShortcutsRoute: typeof ShortcutsRoute
  TrialRunRoute: typeof TrialRunRoute
  CliSessionsRunIdRoute: typeof CliSessionsRunIdRoute
  ObservabilitySessionsRoute: typeof ObservabilitySessionsRouteWithChildren
  CliSessionsIndexRoute: typeof CliSessionsIndexRoute
  AdminDebugCalibrationRoute: typeof AdminDebugCalibrationRoute
  AdminDebugCalibrationDistributionsRoute: typeof AdminDebugCalibrationDistributionsRoute
  AdminSecurityDenialBurstRoute: typeof AdminSecurityDenialBurstRoute
  ApiCameraCaptureRoute: typeof ApiCameraCaptureRoute
  ApiCameraDefaultsRoute: typeof ApiCameraDefaultsRoute
  ObservabilityRunsRunIdRoute: typeof ObservabilityRunsRunIdRoute
  ApiPublicHealthLiveRoute: typeof ApiPublicHealthLiveRoute
  ApiPublicHealthReadyRoute: typeof ApiPublicHealthReadyRoute
  ApiPublicHooksAuditRetentionRoute: typeof ApiPublicHooksAuditRetentionRoute
  ApiCliIpcMsgIdRequeueRoute: typeof ApiCliIpcMsgIdRequeueRoute
  ApiCliSessionsRunIdExportRoute: typeof ApiCliSessionsRunIdExportRoute
  ApiCliSessionsRunIdLogRoute: typeof ApiCliSessionsRunIdLogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trial-run': {
      id: '/trial-run'
      path: '/trial-run'
      fullPath: '/trial-run'
      preLoaderRoute: typeof TrialRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortcuts': {
      id: '/shortcuts'
      path: '/shortcuts'
      fullPath: '/shortcuts'
      preLoaderRoute: typeof ShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-testing': {
      id: '/ai-testing'
      path: '/ai-testing'
      fullPath: '/ai-testing'
      preLoaderRoute: typeof AiTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/cli/': {
      id: '/cli/'
      path: '/'
      fullPath: '/cli/'
      preLoaderRoute: typeof CliIndexRouteImport
      parentRoute: typeof CliRoute
    }
    '/cli-sessions/': {
      id: '/cli-sessions/'
      path: '/cli-sessions'
      fullPath: '/cli-sessions/'
      preLoaderRoute: typeof CliSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/rules': {
      id: '/setup/rules'
      path: '/rules'
      fullPath: '/setup/rules'
      preLoaderRoute: typeof SetupRulesRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/roi': {
      id: '/setup/roi'
      path: '/roi'
      fullPath: '/setup/roi'
      preLoaderRoute: typeof SetupRoiRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/reference': {
      id: '/setup/reference'
      path: '/reference'
      fullPath: '/setup/reference'
      preLoaderRoute: typeof SetupReferenceRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/functions': {
      id: '/setup/functions'
      path: '/functions'
      fullPath: '/setup/functions'
      preLoaderRoute: typeof SetupFunctionsRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/chain-events': {
      id: '/setup/chain-events'
      path: '/chain-events'
      fullPath: '/setup/chain-events'
      preLoaderRoute: typeof SetupChainEventsRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/categories': {
      id: '/setup/categories'
      path: '/categories'
      fullPath: '/setup/categories'
      preLoaderRoute: typeof SetupCategoriesRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/camera': {
      id: '/setup/camera'
      path: '/camera'
      fullPath: '/setup/camera'
      preLoaderRoute: typeof SetupCameraRouteImport
      parentRoute: typeof SetupRoute
    }
    '/settings/trigger': {
      id: '/settings/trigger'
      path: '/trigger'
      fullPath: '/settings/trigger'
      preLoaderRoute: typeof SettingsTriggerRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/lighting': {
      id: '/settings/lighting'
      path: '/lighting'
      fullPath: '/settings/lighting'
      preLoaderRoute: typeof SettingsLightingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/license': {
      id: '/settings/license'
      path: '/license'
      fullPath: '/settings/license'
      preLoaderRoute: typeof SettingsLicenseRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/camera': {
      id: '/settings/camera'
      path: '/camera'
      fullPath: '/settings/camera'
      preLoaderRoute: typeof SettingsCameraRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/observability/sessions': {
      id: '/observability/sessions'
      path: '/observability/sessions'
      fullPath: '/observability/sessions'
      preLoaderRoute: typeof ObservabilitySessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/settings': {
      id: '/cli/settings'
      path: '/settings'
      fullPath: '/cli/settings'
      preLoaderRoute: typeof CliSettingsRouteImport
      parentRoute: typeof CliRoute
    }
    '/cli/sessions': {
      id: '/cli/sessions'
      path: '/sessions'
      fullPath: '/cli/sessions'
      preLoaderRoute: typeof CliSessionsRouteImport
      parentRoute: typeof CliRoute
    }
    '/cli/samples': {
      id: '/cli/samples'
      path: '/samples'
      fullPath: '/cli/samples'
      preLoaderRoute: typeof CliSamplesRouteImport
      parentRoute: typeof CliRoute
    }
    '/cli/rules': {
      id: '/cli/rules'
      path: '/rules'
      fullPath: '/cli/rules'
      preLoaderRoute: typeof CliRulesRouteImport
      parentRoute: typeof CliRoute
    }
    '/cli/ipc': {
      id: '/cli/ipc'
      path: '/ipc'
      fullPath: '/cli/ipc'
      preLoaderRoute: typeof CliIpcRouteImport
      parentRoute: typeof CliRoute
    }
    '/cli-sessions/$runId': {
      id: '/cli-sessions/$runId'
      path: '/cli-sessions/$runId'
      fullPath: '/cli-sessions/$runId'
      preLoaderRoute: typeof CliSessionsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/categories/': {
      id: '/setup/categories/'
      path: '/'
      fullPath: '/setup/categories/'
      preLoaderRoute: typeof SetupCategoriesIndexRouteImport
      parentRoute: typeof SetupCategoriesRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/setup/rules/$id': {
      id: '/setup/rules/$id'
      path: '/$id'
      fullPath: '/setup/rules/$id'
      preLoaderRoute: typeof SetupRulesIdRouteImport
      parentRoute: typeof SetupRulesRoute
    }
    '/setup/categories/$id': {
      id: '/setup/categories/$id'
      path: '/$id'
      fullPath: '/setup/categories/$id'
      preLoaderRoute: typeof SetupCategoriesIdRouteImport
      parentRoute: typeof SetupCategoriesRoute
    }
    '/projects/$projectId/trial-run': {
      id: '/projects/$projectId/trial-run'
      path: '/trial-run'
      fullPath: '/projects/$projectId/trial-run'
      preLoaderRoute: typeof ProjectsProjectIdTrialRunRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/runs': {
      id: '/projects/$projectId/runs'
      path: '/runs'
      fullPath: '/projects/$projectId/runs'
      preLoaderRoute: typeof ProjectsProjectIdRunsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/rulesets': {
      id: '/projects/$projectId/rulesets'
      path: '/rulesets'
      fullPath: '/projects/$projectId/rulesets'
      preLoaderRoute: typeof ProjectsProjectIdRulesetsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/categories': {
      id: '/projects/$projectId/categories'
      path: '/categories'
      fullPath: '/projects/$projectId/categories'
      preLoaderRoute: typeof ProjectsProjectIdCategoriesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/camera': {
      id: '/projects/$projectId/camera'
      path: '/camera'
      fullPath: '/projects/$projectId/camera'
      preLoaderRoute: typeof ProjectsProjectIdCameraRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/ai-testing-history': {
      id: '/projects/$projectId/ai-testing-history'
      path: '/ai-testing-history'
      fullPath: '/projects/$projectId/ai-testing-history'
      preLoaderRoute: typeof ProjectsProjectIdAiTestingHistoryRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/ai-testing': {
      id: '/projects/$projectId/ai-testing'
      path: '/ai-testing'
      fullPath: '/projects/$projectId/ai-testing'
      preLoaderRoute: typeof ProjectsProjectIdAiTestingRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/observability/runs/$runId': {
      id: '/observability/runs/$runId'
      path: '/observability/runs/$runId'
      fullPath: '/observability/runs/$runId'
      preLoaderRoute: typeof ObservabilityRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/sessions/compare': {
      id: '/cli/sessions/compare'
      path: '/compare'
      fullPath: '/cli/sessions/compare'
      preLoaderRoute: typeof CliSessionsCompareRouteImport
      parentRoute: typeof CliSessionsRoute
    }
    '/cli/sessions/$sessionId': {
      id: '/cli/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/cli/sessions/$sessionId'
      preLoaderRoute: typeof CliSessionsSessionIdRouteImport
      parentRoute: typeof CliSessionsRoute
    }
    '/cli/samples/$sampleId': {
      id: '/cli/samples/$sampleId'
      path: '/$sampleId'
      fullPath: '/cli/samples/$sampleId'
      preLoaderRoute: typeof CliSamplesSampleIdRouteImport
      parentRoute: typeof CliSamplesRoute
    }
    '/cli/rules/import': {
      id: '/cli/rules/import'
      path: '/import'
      fullPath: '/cli/rules/import'
      preLoaderRoute: typeof CliRulesImportRouteImport
      parentRoute: typeof CliRulesRoute
    }
    '/cli/rules/$ruleId': {
      id: '/cli/rules/$ruleId'
      path: '/$ruleId'
      fullPath: '/cli/rules/$ruleId'
      preLoaderRoute: typeof CliRulesRuleIdRouteImport
      parentRoute: typeof CliRulesRoute
    }
    '/api/camera/defaults': {
      id: '/api/camera/defaults'
      path: '/api/camera/defaults'
      fullPath: '/api/camera/defaults'
      preLoaderRoute: typeof ApiCameraDefaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/camera/capture': {
      id: '/api/camera/capture'
      path: '/api/camera/capture'
      fullPath: '/api/camera/capture'
      preLoaderRoute: typeof ApiCameraCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security/denial-burst': {
      id: '/admin/security/denial-burst'
      path: '/admin/security/denial-burst'
      fullPath: '/admin/security/denial-burst'
      preLoaderRoute: typeof AdminSecurityDenialBurstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/debug/calibration-distributions': {
      id: '/admin/debug/calibration-distributions'
      path: '/admin/debug/calibration-distributions'
      fullPath: '/admin/debug/calibration-distributions'
      preLoaderRoute: typeof AdminDebugCalibrationDistributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/debug/calibration': {
      id: '/admin/debug/calibration'
      path: '/admin/debug/calibration'
      fullPath: '/admin/debug/calibration'
      preLoaderRoute: typeof AdminDebugCalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/rulesets/': {
      id: '/projects/$projectId/rulesets/'
      path: '/'
      fullPath: '/projects/$projectId/rulesets/'
      preLoaderRoute: typeof ProjectsProjectIdRulesetsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRulesetsRoute
    }
    '/projects/$projectId/trial-run/$runId': {
      id: '/projects/$projectId/trial-run/$runId'
      path: '/$runId'
      fullPath: '/projects/$projectId/trial-run/$runId'
      preLoaderRoute: typeof ProjectsProjectIdTrialRunRunIdRouteImport
      parentRoute: typeof ProjectsProjectIdTrialRunRoute
    }
    '/projects/$projectId/rulesets/new': {
      id: '/projects/$projectId/rulesets/new'
      path: '/new'
      fullPath: '/projects/$projectId/rulesets/new'
      preLoaderRoute: typeof ProjectsProjectIdRulesetsNewRouteImport
      parentRoute: typeof ProjectsProjectIdRulesetsRoute
    }
    '/projects/$projectId/rulesets/$rulesetId': {
      id: '/projects/$projectId/rulesets/$rulesetId'
      path: '/$rulesetId'
      fullPath: '/projects/$projectId/rulesets/$rulesetId'
      preLoaderRoute: typeof ProjectsProjectIdRulesetsRulesetIdRouteImport
      parentRoute: typeof ProjectsProjectIdRulesetsRoute
    }
    '/observability/sessions/$cliInvocationId/logs': {
      id: '/observability/sessions/$cliInvocationId/logs'
      path: '/$cliInvocationId/logs'
      fullPath: '/observability/sessions/$cliInvocationId/logs'
      preLoaderRoute: typeof ObservabilitySessionsCliInvocationIdLogsRouteImport
      parentRoute: typeof ObservabilitySessionsRoute
    }
    '/observability/sessions/$cliInvocationId/ipc': {
      id: '/observability/sessions/$cliInvocationId/ipc'
      path: '/$cliInvocationId/ipc'
      fullPath: '/observability/sessions/$cliInvocationId/ipc'
      preLoaderRoute: typeof ObservabilitySessionsCliInvocationIdIpcRouteImport
      parentRoute: typeof ObservabilitySessionsRoute
    }
    '/api/public/hooks/audit-retention': {
      id: '/api/public/hooks/audit-retention'
      path: '/api/public/hooks/audit-retention'
      fullPath: '/api/public/hooks/audit-retention'
      preLoaderRoute: typeof ApiPublicHooksAuditRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/ready': {
      id: '/api/public/health/ready'
      path: '/api/public/health/ready'
      fullPath: '/api/public/health/ready'
      preLoaderRoute: typeof ApiPublicHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/live': {
      id: '/api/public/health/live'
      path: '/api/public/health/live'
      fullPath: '/api/public/health/live'
      preLoaderRoute: typeof ApiPublicHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/sessions/$runId/log': {
      id: '/api/cli/sessions/$runId/log'
      path: '/api/cli/sessions/$runId/log'
      fullPath: '/api/cli/sessions/$runId/log'
      preLoaderRoute: typeof ApiCliSessionsRunIdLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/sessions/$runId/export': {
      id: '/api/cli/sessions/$runId/export'
      path: '/api/cli/sessions/$runId/export'
      fullPath: '/api/cli/sessions/$runId/export'
      preLoaderRoute: typeof ApiCliSessionsRunIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/ipc/$msgId/requeue': {
      id: '/api/cli/ipc/$msgId/requeue'
      path: '/api/cli/ipc/$msgId/requeue'
      fullPath: '/api/cli/ipc/$msgId/requeue'
      preLoaderRoute: typeof ApiCliIpcMsgIdRequeueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/rulesets/$rulesetId/rules/$ruleId': {
      id: '/projects/$projectId/rulesets/$rulesetId/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/projects/$projectId/rulesets/$rulesetId/rules/$ruleId'
      preLoaderRoute: typeof ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRouteImport
      parentRoute: typeof ProjectsProjectIdRulesetsRulesetIdRoute
    }
  }
}

interface CliRulesRouteChildren {
  CliRulesRuleIdRoute: typeof CliRulesRuleIdRoute
  CliRulesImportRoute: typeof CliRulesImportRoute
}

const CliRulesRouteChildren: CliRulesRouteChildren = {
  CliRulesRuleIdRoute: CliRulesRuleIdRoute,
  CliRulesImportRoute: CliRulesImportRoute,
}

const CliRulesRouteWithChildren = CliRulesRoute._addFileChildren(
  CliRulesRouteChildren,
)

interface CliSamplesRouteChildren {
  CliSamplesSampleIdRoute: typeof CliSamplesSampleIdRoute
}

const CliSamplesRouteChildren: CliSamplesRouteChildren = {
  CliSamplesSampleIdRoute: CliSamplesSampleIdRoute,
}

const CliSamplesRouteWithChildren = CliSamplesRoute._addFileChildren(
  CliSamplesRouteChildren,
)

interface CliSessionsRouteChildren {
  CliSessionsSessionIdRoute: typeof CliSessionsSessionIdRoute
  CliSessionsCompareRoute: typeof CliSessionsCompareRoute
}

const CliSessionsRouteChildren: CliSessionsRouteChildren = {
  CliSessionsSessionIdRoute: CliSessionsSessionIdRoute,
  CliSessionsCompareRoute: CliSessionsCompareRoute,
}

const CliSessionsRouteWithChildren = CliSessionsRoute._addFileChildren(
  CliSessionsRouteChildren,
)

interface CliRouteChildren {
  CliIpcRoute: typeof CliIpcRoute
  CliRulesRoute: typeof CliRulesRouteWithChildren
  CliSamplesRoute: typeof CliSamplesRouteWithChildren
  CliSessionsRoute: typeof CliSessionsRouteWithChildren
  CliSettingsRoute: typeof CliSettingsRoute
  CliIndexRoute: typeof CliIndexRoute
}

const CliRouteChildren: CliRouteChildren = {
  CliIpcRoute: CliIpcRoute,
  CliRulesRoute: CliRulesRouteWithChildren,
  CliSamplesRoute: CliSamplesRouteWithChildren,
  CliSessionsRoute: CliSessionsRouteWithChildren,
  CliSettingsRoute: CliSettingsRoute,
  CliIndexRoute: CliIndexRoute,
}

const CliRouteWithChildren = CliRoute._addFileChildren(CliRouteChildren)

interface ProjectsProjectIdRulesetsRulesetIdRouteChildren {
  ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRoute: typeof ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRoute
}

const ProjectsProjectIdRulesetsRulesetIdRouteChildren: ProjectsProjectIdRulesetsRulesetIdRouteChildren =
  {
    ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRoute:
      ProjectsProjectIdRulesetsRulesetIdRulesRuleIdRoute,
  }

const ProjectsProjectIdRulesetsRulesetIdRouteWithChildren =
  ProjectsProjectIdRulesetsRulesetIdRoute._addFileChildren(
    ProjectsProjectIdRulesetsRulesetIdRouteChildren,
  )

interface ProjectsProjectIdRulesetsRouteChildren {
  ProjectsProjectIdRulesetsRulesetIdRoute: typeof ProjectsProjectIdRulesetsRulesetIdRouteWithChildren
  ProjectsProjectIdRulesetsNewRoute: typeof ProjectsProjectIdRulesetsNewRoute
  ProjectsProjectIdRulesetsIndexRoute: typeof ProjectsProjectIdRulesetsIndexRoute
}

const ProjectsProjectIdRulesetsRouteChildren: ProjectsProjectIdRulesetsRouteChildren =
  {
    ProjectsProjectIdRulesetsRulesetIdRoute:
      ProjectsProjectIdRulesetsRulesetIdRouteWithChildren,
    ProjectsProjectIdRulesetsNewRoute: ProjectsProjectIdRulesetsNewRoute,
    ProjectsProjectIdRulesetsIndexRoute: ProjectsProjectIdRulesetsIndexRoute,
  }

const ProjectsProjectIdRulesetsRouteWithChildren =
  ProjectsProjectIdRulesetsRoute._addFileChildren(
    ProjectsProjectIdRulesetsRouteChildren,
  )

interface ProjectsProjectIdTrialRunRouteChildren {
  ProjectsProjectIdTrialRunRunIdRoute: typeof ProjectsProjectIdTrialRunRunIdRoute
}

const ProjectsProjectIdTrialRunRouteChildren: ProjectsProjectIdTrialRunRouteChildren =
  {
    ProjectsProjectIdTrialRunRunIdRoute: ProjectsProjectIdTrialRunRunIdRoute,
  }

const ProjectsProjectIdTrialRunRouteWithChildren =
  ProjectsProjectIdTrialRunRoute._addFileChildren(
    ProjectsProjectIdTrialRunRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdAiTestingRoute: typeof ProjectsProjectIdAiTestingRoute
  ProjectsProjectIdAiTestingHistoryRoute: typeof ProjectsProjectIdAiTestingHistoryRoute
  ProjectsProjectIdCameraRoute: typeof ProjectsProjectIdCameraRoute
  ProjectsProjectIdCategoriesRoute: typeof ProjectsProjectIdCategoriesRoute
  ProjectsProjectIdRulesetsRoute: typeof ProjectsProjectIdRulesetsRouteWithChildren
  ProjectsProjectIdRunsRoute: typeof ProjectsProjectIdRunsRoute
  ProjectsProjectIdTrialRunRoute: typeof ProjectsProjectIdTrialRunRouteWithChildren
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdAiTestingRoute: ProjectsProjectIdAiTestingRoute,
  ProjectsProjectIdAiTestingHistoryRoute:
    ProjectsProjectIdAiTestingHistoryRoute,
  ProjectsProjectIdCameraRoute: ProjectsProjectIdCameraRoute,
  ProjectsProjectIdCategoriesRoute: ProjectsProjectIdCategoriesRoute,
  ProjectsProjectIdRulesetsRoute: ProjectsProjectIdRulesetsRouteWithChildren,
  ProjectsProjectIdRunsRoute: ProjectsProjectIdRunsRoute,
  ProjectsProjectIdTrialRunRoute: ProjectsProjectIdTrialRunRouteWithChildren,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsCameraRoute: typeof SettingsCameraRoute
  SettingsLicenseRoute: typeof SettingsLicenseRoute
  SettingsLightingRoute: typeof SettingsLightingRoute
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  SettingsTriggerRoute: typeof SettingsTriggerRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCameraRoute: SettingsCameraRoute,
  SettingsLicenseRoute: SettingsLicenseRoute,
  SettingsLightingRoute: SettingsLightingRoute,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  SettingsTriggerRoute: SettingsTriggerRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SetupCategoriesRouteChildren {
  SetupCategoriesIdRoute: typeof SetupCategoriesIdRoute
  SetupCategoriesIndexRoute: typeof SetupCategoriesIndexRoute
}

const SetupCategoriesRouteChildren: SetupCategoriesRouteChildren = {
  SetupCategoriesIdRoute: SetupCategoriesIdRoute,
  SetupCategoriesIndexRoute: SetupCategoriesIndexRoute,
}

const SetupCategoriesRouteWithChildren = SetupCategoriesRoute._addFileChildren(
  SetupCategoriesRouteChildren,
)

interface SetupRulesRouteChildren {
  SetupRulesIdRoute: typeof SetupRulesIdRoute
}

const SetupRulesRouteChildren: SetupRulesRouteChildren = {
  SetupRulesIdRoute: SetupRulesIdRoute,
}

const SetupRulesRouteWithChildren = SetupRulesRoute._addFileChildren(
  SetupRulesRouteChildren,
)

interface SetupRouteChildren {
  SetupCameraRoute: typeof SetupCameraRoute
  SetupCategoriesRoute: typeof SetupCategoriesRouteWithChildren
  SetupChainEventsRoute: typeof SetupChainEventsRoute
  SetupFunctionsRoute: typeof SetupFunctionsRoute
  SetupReferenceRoute: typeof SetupReferenceRoute
  SetupRoiRoute: typeof SetupRoiRoute
  SetupRulesRoute: typeof SetupRulesRouteWithChildren
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupCameraRoute: SetupCameraRoute,
  SetupCategoriesRoute: SetupCategoriesRouteWithChildren,
  SetupChainEventsRoute: SetupChainEventsRoute,
  SetupFunctionsRoute: SetupFunctionsRoute,
  SetupReferenceRoute: SetupReferenceRoute,
  SetupRoiRoute: SetupRoiRoute,
  SetupRulesRoute: SetupRulesRouteWithChildren,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

interface ObservabilitySessionsRouteChildren {
  ObservabilitySessionsCliInvocationIdIpcRoute: typeof ObservabilitySessionsCliInvocationIdIpcRoute
  ObservabilitySessionsCliInvocationIdLogsRoute: typeof ObservabilitySessionsCliInvocationIdLogsRoute
}

const ObservabilitySessionsRouteChildren: ObservabilitySessionsRouteChildren = {
  ObservabilitySessionsCliInvocationIdIpcRoute:
    ObservabilitySessionsCliInvocationIdIpcRoute,
  ObservabilitySessionsCliInvocationIdLogsRoute:
    ObservabilitySessionsCliInvocationIdLogsRoute,
}

const ObservabilitySessionsRouteWithChildren =
  ObservabilitySessionsRoute._addFileChildren(
    ObservabilitySessionsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiTestingRoute: AiTestingRoute,
  CliRoute: CliRouteWithChildren,
  DiagnosticsRoute: DiagnosticsRoute,
  ErrorsRoute: ErrorsRoute,
  OpsRoute: OpsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResultsRoute: ResultsRoute,
  RunRoute: RunRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRouteWithChildren,
  ShortcutsRoute: ShortcutsRoute,
  TrialRunRoute: TrialRunRoute,
  CliSessionsRunIdRoute: CliSessionsRunIdRoute,
  ObservabilitySessionsRoute: ObservabilitySessionsRouteWithChildren,
  CliSessionsIndexRoute: CliSessionsIndexRoute,
  AdminDebugCalibrationRoute: AdminDebugCalibrationRoute,
  AdminDebugCalibrationDistributionsRoute:
    AdminDebugCalibrationDistributionsRoute,
  AdminSecurityDenialBurstRoute: AdminSecurityDenialBurstRoute,
  ApiCameraCaptureRoute: ApiCameraCaptureRoute,
  ApiCameraDefaultsRoute: ApiCameraDefaultsRoute,
  ObservabilityRunsRunIdRoute: ObservabilityRunsRunIdRoute,
  ApiPublicHealthLiveRoute: ApiPublicHealthLiveRoute,
  ApiPublicHealthReadyRoute: ApiPublicHealthReadyRoute,
  ApiPublicHooksAuditRetentionRoute: ApiPublicHooksAuditRetentionRoute,
  ApiCliIpcMsgIdRequeueRoute: ApiCliIpcMsgIdRequeueRoute,
  ApiCliSessionsRunIdExportRoute: ApiCliSessionsRunIdExportRoute,
  ApiCliSessionsRunIdLogRoute: ApiCliSessionsRunIdLogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
